### ISSUE TITLE
"Compare by" doesn't trim buckets?

### ISSUE THREAD

**Issue by vdjeric** [mozilla/telemetry-dashboard#135]
The 0.00% buckets on the right side of this view aren't getting trimmed: http://bit.ly/1LikR8Q

**Comment by Uberi** [comment]
On that page the last bucket still has a significant amount of samples, so we're not supposed to trim:

![untitled](https://cloud.githubusercontent.com/assets/437196/9363482/bd2ad44c-4674-11e5-9258-5bdcfcb8aa86.png)

The current compare behaviour is to trim from both ends as long as there are an insignificant number of samples in those buckets.

**Comment by vdjeric** [comment]
Oh i see, I missed the final bucket having more than 0.01%. Maybe we should raise the threshold in the future. Closing this issue.
