### ISSUE TITLE
Bug in Histogram table-view

### ISSUE THREAD

**Issue by vdjeric** [mozilla/telemetry-dashboard#136]
Go to http://bit.ly/1LileQP and select between "Sanitize" and "Don't sanitize".

First 2 table rows with "Sanitize":

Start	|End	|Windows Vista Count	|Windows 8.1 Count	|Windows 7 Count	|**Windows 10 Count**
------------ | -------------  | -------------  | -------------  | ------------- | -------------
1	| 22	| 568.66k	| 1.18M	| 817.7k	| **98.15k**

First 2 table rows with "Don't sanitize":

Start	|End	|Windows Vista Count	|Windows 8.1 Count	|Windows 7 Count	|Windows 10 Count	|**Windows 8 Count**
------------ | -------------  | -------------  | -------------  | ------------- | ------------- | -------------
1	| 22	| 4.09k	| 568.66k	| 1.18M	| 817.7k	| **98.15k**

Note how the last column is no longer "Windows 10 count" and is instead "Windows 8 count", but the sample count in the last column is unchanged?

**Comment by vdjeric** [comment]
Note that "Export" functionality is also affected

**Comment by Uberi** [comment]
I can't seem to reproduce this using the permalink above, on the current release/aurora or on Chrome.

**Comment by Uberi** [comment]
This is fixed as of #146.
