### ISSUE TITLE
Boolean evolution graph should plot the proportion over time

### ISSUE THREAD

**Issue by mnoorenberghe** [mozilla/telemetry-dashboard#155]
Thanks for working on boolean and enumerated evolution!

Looking at PWMGR_SAVING_ENABLED (boolean) in the evolution view, the obvious thing I would want to see is the proportion of true vs. false over time. Instead I get a mean plotted with a consistent value of 1.01. How am I supposed to interpret this graph? The histogram for beta 40 shows as 95.79/4.21 split.

**Comment by Uberi** [comment]
Fixed in #153.

**Comment by mnoorenberghe** [comment]
Verified fixed. I can choose the "True percentage" now to get what I want. Thanks for the quick fixes!
