### ISSUE TITLE
Probe selector regularly switches to a different probe when changing parameters e.g. version pickers

### ISSUE THREAD

**Issue by mnoorenberghe** [mozilla/telemetry-dashboard#158]
IMO the probe name should never change on me as it's very annoying have to change it back and it's not always obvious that it's happening.

**Comment by Uberi** [comment]
It is definitely a bug if the probe changes even though it is still valid - how and when does this happen? What is your browser version?

**Comment by mnoorenberghe** [comment]
This was Nightly but I suspect it may have been caused by #154 and/or the timeouts I was seeing for Beta data mentioned in #161. I don't have good STR as I wasn't specifically looking for a bug when it happened. I'm fine with closing this until I see it again.
