### ISSUE TITLE
Telemetry Dashboard no longer supports Thunderbird

### ISSUE THREAD

**Issue by Standard8** [mozilla/telemetry-dashboard#16]
The telemetry dashboard seems to no longer support viewing Thunderbird application details. It used to when Metrics ran it on their server.

AFAICT there's now no longer a way to view Thunderbird stats, so I can't even tell if they are being sent & received or not :-(

**Comment by chutten** [comment]
It seems as though there are [some samples](http://mzl.la/1HkP8G2) for Thunderbird on the current telemetry-dashboard on t.m.o

**Comment by vdjeric** [comment]
Should we close this issue?
