### ISSUE TITLE
Modal (evo) progress indicator doesn't go away/notify upon fatal error

### ISSUE THREAD

**Issue by mnoorenberghe** [mozilla/telemetry-dashboard#161]
http://aggregates.telemetry.mozilla.org/aggregates_by/build_id/channels/nightly/?version=42&dates=20150813%2C20150811%2C20150810%2C20150809%2C20150808%2C20150807%2C20150806%2C20150805%2C20150804%2C20150803%2C20150802%2C20150801%2C20150731%2C20150730%2C20150729%2C20150728%2C20150727%2C20150726%2C20150725%2C20150724%2C20150723%2C20150722%2C20150721%2C20150720%2C20150719%2C20150718%2C20150717%2C20150716%2C20150715%2C20150714%2C20150713%2C20150712%2C20150711%2C20150710%2C20150709%2C20150708%2C20150707%2C20150706%2C20150705%2C20150704%2C20150703%2C20150702%2C20150701%2C20150630%2C20150629&metric=GHOST_WINDOWS&application=Firefox
HTTP/1.1 504 GATEWAY_TIMEOUT

uncaught exception: Could not obtain evolution: status 0 (http://aggregates.telemetry.mozilla.org/aggregates_by/build_id/channels/nightly/?version=42&dates=20150813%2C20150811%2C20150810%2C20150809%2C20150808%2C20150807%2C20150806%2C20150805%2C20150804%2C20150803%2C20150802%2C20150801%2C20150731%2C20150730%2C20150729%2C20150728%2C20150727%2C20150726%2C20150725%2C20150724%2C20150723%2C20150722%2C20150721%2C20150720%2C20150719%2C20150718%2C20150717%2C20150716%2C20150715%2C20150714%2C20150713%2C20150712%2C20150711%2C20150710%2C20150709%2C20150708%2C20150707%2C20150706%2C20150705%2C20150704%2C20150703%2C20150702%2C20150701%2C20150630%2C20150629&metric=GHOST_WINDOWS&application=Firefox)

The gear kept spinning indefinitely and wouldn't allow retrying, changing parameters or reloading the page (as the page doesn't seem to keep state and would reset to default values; filing a separate issue on this)

**Comment by Uberi** [comment]
Fixed in #153.
