### ISSUE TITLE
Mixed content in Histogram Dashboard prevents it from loading over HTTPS

### ISSUE THREAD

**Issue by fmarier** [mozilla/telemetry-dashboard#163]
If I load https://telemetry.mozilla.org/new-pipeline/dist.html (HTTPS URL), I see the following in the devtool console:

    Blocked loading mixed active content "http://aggregates.telemetry.mozilla.org/aggregates_by/build_id/channels/"

This is breaking the page.

**Comment by Uberi** [comment]
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1195802

**Comment by vdjeric** [comment]
Solved in pull #175
