### ISSUE TITLE
CORS request blocked

### ISSUE THREAD

**Issue by vdjeric** [mozilla/telemetry-dashboard#166]
Is this error unique to the divshot.io deployement?

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://aggregates.telemetry.mozilla.org/aggregates_by/submission_date/channels/nightly/?version=42&dates=20150818,20150817,20150816,20150815,20150814,20150813,20150812,20150811,20150810,20150808,20150807,20150806,20150805,20150804,20150803,20150802,20150801,20150731,20150727,20150726,20150725,20150724,20150723,20150722,20150721,20150720,20150719,20150718,20150717,20150716,20150715,20150714,20150713,20150712,20150711,20150710,20150709,20150708,20150707,20150706,20150705,20150704,20150703,20150702,20150701&metric=JS_TELEMETRY_ADDON_EXCEPTIONS. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

**Comment by vitillo** [comment]
I can load the data directly from the browser, it's about 40 MB though. Ideally we shouldn't load that many dates when we first display a keyed histogram.

**Comment by Uberi** [comment]
This would probably be solved with lazy loading. To make it work in the evolution view though, we need a new endpoint that provides histogram metadata like kind, description, and bucket values.

At the moment, it is not possible to reliably do so without downloading entries for all the dates. For example, [20150810](http://aggregates.telemetry.mozilla.org/aggregates_by/submission_date/channels/nightly/dates/) is a valid date, but it has [no values for CACHE_SERVICE_LOCK_WAIT_MAINTHREAD_NSCACHEENTRYDESCRIPTOR_CLOSE](http://aggregates.telemetry.mozilla.org/aggregates_by/submission_date/channels/nightly/?version=43&dates=20150810&metric=CACHE_SERVICE_LOCK_WAIT_MAINTHREAD_NSCACHEENTRYDESCRIPTOR_CLOSE).

**Comment by chutten** [comment]
The original issue is not sending CORS headers for error responses which is https://bugzilla.mozilla.org/show_bug.cgi?id=1353780
