### ISSUE TITLE
Line color being re-used in Evo view

### ISSUE THREAD

**Issue by vdjeric** [mozilla/telemetry-dashboard#168]
Same color being used for different versions: http://bit.ly/1Np1rSM

**Comment by Uberi** [comment]
I can't seem to reproduce this using that permalink, but the current behaviour is to reuse colors if there are too many.

We originally had random colors but they ended up sometimes looking too similar. There was also the behaviour a while ago where we generate colors using a fixed value, changing hue, and two different saturations, but this had the same problem.

Should I just add more colors?

**Comment by vdjeric** [comment]
yeah my link doesn't reproduce it either.. ignore for now
