### ISSUE TITLE
Change "data missing" message

### ISSUE THREAD

**Issue by vdjeric** [mozilla/telemetry-dashboard#171]
Change the "Data currently missing or unavailable" string to "No data matching these filters and settings". And suggest "Turn off data sanitization in Advanced Settings?" if sanitization is enabled

**Comment by Uberi** [comment]
![untitled](https://cloud.githubusercontent.com/assets/437196/9420614/9477998c-4835-11e5-9f72-c2e653cd9667.png)

**Comment by vdjeric** [comment]
Suggested wording: 

No data matches these filters and settings. 

Possible reasons:
1) The Telemetry submissions haven't been aggregated for the dashboard yet (it takes a couple of days)
2) Too few submissions were received & are being filtered out in the dash. Turn off "Sanitize data" in Advanced Settings panel? 
3) The data was sent to Telemetry before the unified Telemetry pipeline came online (July 2015)
