### ISSUE TITLE
Probe selector loses its filter upon re-opening

### ISSUE THREAD

**Issue by mnoorenberghe** [mozilla/telemetry-dashboard#176]
When I re-open the probe dropdown after having selected a new probe, the popup initially opens with the list pre-filtered or at least scrolled but then switches to a unfiltered view from the top. Ideally the filter the should be remembered since one normally wants to look at related probes e.g. all `PWMGR_` ones

I think this may be a regression since I don't think this happened a month ago.

![telemetry_dash_filter_revert](https://cloud.githubusercontent.com/assets/601139/9510794/ce35ac84-4c24-11e5-978a-829cf50a866c.gif)

**Comment by mnoorenberghe** [comment]
This is the newest evo dashboard btw.

**Comment by vdjeric** [comment]
I actually asked for this in https://github.com/mozilla/telemetry-dashboard/issues/167
:)
Maybe we can compromise on having the box blank but the list cued to the right position?

**Comment by mnoorenberghe** [comment]
That would work for the most common case where the same prefix is used so is better than the current behaviour. What was your use case for #167?

**Comment by mnoorenberghe** [comment]
Another idea would be to revert #167 but have the filter text selected and focused so it's simple to type over it.

**Comment by Uberi** [comment]
IIRC the original reason for #167 was the need to clear the filter box every time you wanted to change filters, which is an extra click/keystroke.

**Comment by vdjeric** [comment]
Merged & deployed #177
