### ISSUE TITLE
Keyed histogram dash should only show the histogram legend once

### ISSUE THREAD

**Issue by vdjeric** [mozilla/telemetry-dashboard#184]
For example on: http://mzl.la/1FLffVs
... the histogram description "Counts number of times a certain plugin has been activated" should only be shown once, right under the dashboard filters (same as non-keyed histograms) and not under each keyed histogram where it creates clutter

**Comment by mnoorenberghe** [comment]
While we're fixing this can we also make it so long ones aren't truncated and the text is selectable (i.e. move it out of the graph image)

**Comment by vdjeric** [comment]
@chutten do you want to take a look

**Comment by chutten** [comment]
@vdjeric The histogram description is only ever shown as an axis label under a plot, in both keyed and unkeyed histograms... or at least I cannot seem to make it appear anywhere else. Do you have a link or screenshot showing the description appearing elsewhere?

**Comment by vdjeric** [comment]
My complaint is that the histogram description is repeated for each key (i.e. 4 times on one page). I was suggesting we only show the description once, above all the histograms.
Matt was suggesting we make that text selectable. I think moving the histogram description description above the histograms would address MattN's suggestion as well.

**Comment by chutten** [comment]
Ah, not emulating any existing behaviour. Sure, that information is easily available.

**Comment by chutten** [comment]
The data scientist in me won't allow me to remove labels from one of the axes. The first (and possibly the only that I remember) rule of data science is to label your axes. Luckily, with the new title catching users' eyes, the repetition isn't so annoying. Take a look: http://mzl.la/1QRYOdV

Unfortunately, this puts the histograms' descriptions front and centre. And they aren't 
* of consistent quality (GC_MS' "Time spent running JS GC (ms)" is lovely, especially compared to SEARCH_COUNTS' "Record the search counts for search engines"),
* always present (it appears no simple measures have descriptions at all),
* or grammatically correct (COMPOSITE_FRAME_ROUNDTRIP_TIME's "Time from vsync to finishing a composite in milliseconds." might actually be okay, but you need to look at it sideways).

I don't suppose we're willing to undertake a wholesale text edit of the Histogram description fields, are we @vdjeric ? I suppose we'd feel compelled to i18n them at that point, and then wouldn't we be in a heap of trouble...

**Comment by vdjeric** [comment]
Nah, let's not invest time in fixing the descriptions. If the histogram's authors are ok with how the descriptions appear in the dashes, then that's good enough for me. In the end, we're providing a service to them, not for ourselves.
