### ISSUE TITLE
Export buttons don't export for each key of a keyed histogram

### ISSUE THREAD

**Issue by mnoorenberghe** [mozilla/telemetry-dashboard#193]
I want to have the exported CSV or JSON data by key but I just get one set of data and I'm not sure what it refers to.

**Comment by vdjeric** [comment]
Yup, I can reproduce this on http://mzl.la/1LkfTVV
@chutten can you take a look?

**Comment by chutten** [comment]
Is there a schema that these buttons are mimicking and I should follow, or am I free to break it to fix it?

**Comment by vdjeric** [comment]
There is no schema. It'd be nice to keep the unkeyed histogram format the same, change the keyed histograms' export format as you like as long as it remains valid JSON.

**Comment by chutten** [comment]
How's this? http://chutten.github.io/telemetry-dashboard/new-pipeline/dist.html#!cumulative=0&end_date=2015-11-15&keys=content!plugin!gmplugin!__none__&max_channel_version=nightly%252F45&measure=SUBPROCESS_ABNORMAL_ABORT&min_channel_version=null&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2015-10-29&table=0&trim=1&use_submission_date=0 

With keys, that makes 3-dimensional data, so I'm disinclined to support CSV in the keyed case unless there's a compelling use case for it over JSON.

**Comment by mnoorenberghe** [comment]
> I actually don't know if people need CSV. You could just have the key name on a separate line in the CSV file, but we can also wait and see if anyone complains.

CSV is the one I care about actually. If I want to do a simple one-off graph (like I wanted to yesterday), it's trivial to do that in Google Spreadsheets without writing a single line of code with CSV. Not so much with JSON (though I think Google Sheets actually have some built-in JSON helpers).

I would just denormalize the data with respect to the key and have it repeated on each row (ideally grouped by key first then bucket) and put the key as the last column to not break compat.

> I know I said you can change the keyed histogram format how you like but I figured you'd keep the histogram description for a given key the same as the unkeyed format

Agreed. We shouldn't change more than we need.

**Comment by chutten** [comment]
Alrighty, let's talk schema. The existing schema for JSON is:
```json
[
  {
    "start": "bucket0start",
    "METRIC_NAME": "bucket0Count",
  },
]
```

But only for the non-comparing case. If you are comparing values, `METRIC_NAME: bucketCount` is replaced by `description of comparing value1..N: bucketCount` like so:
```json
[
  {
    "start": "bucket0start",
    "e10s": "bucket0e10sCount",
    "no e10s": "bucket0no e10sCount"
  }
]
```
This is okay, I guess, though there isn't any mention of `METRIC_NAME` in this schema. CSV is similar:
```csv
start, METRIC_NAME
```
vs
```csv
start, e10s, no e10s
```

So, assuming we're leaving those alone, we're looking at, for keyed hists for JSON:
```json
{
  "KEY_NAME": [
    {
      "start": "bucket0start",
      "e10s": "bucket0e10sCount",
      "no e10s": "bucket0no e10sCount"
    }
  ]
}
```
and CSV
```csv
start, key, e10s, no e10s
bucket0start, KEY_NAME, bucket0e10sCount, bucket0no e10sCount
```

Will this work for you, @mnoorenberghe?

**Comment by chutten** [comment]
Alrighty, how about this? http://bit.ly/1I1RPMN

Note you can choose different keys and the exported data will contain those keys in the order shown.

**Comment by vdjeric** [comment]
looks good to me, but MattN is the real end-user

**Comment by mnoorenberghe** [comment]
With @chutten's info about a pivot table:
`Rows: start, Colums: key, Values: (value column)`
this works fine for me

**Comment by vdjeric** [comment]
The "Export JSON" format is a bit odd for unkeyed histograms, no? http://bit.ly/1T5a8kN

**Comment by chutten** [comment]
I specifically left the unkeyed exports alone in case someone depends on the format.

**Comment by vdjeric** [comment]
I didn't realize the unkeyed JSON histogram format was this bad, sorry about that. I'm tempted to say break the format and replace the occurences of the histogram name with the string "count" for both keyed & unkeyed histograms. I don't think any sane person would depend on the histogram name being repeated in every bucket.

With that said, this patch *does* work, so it's entirely your call

**Comment by chutten** [comment]
I say we leave it as it is. Right now the code's barely readable. Adding a `(histograms.length == 1 ? 'count' : histograms[i].measure)` isn't going to help.

Also, this way, if you have the data in some spreadsheet, you have half a chance of remembering what it means :S
