### ISSUE TITLE
Dashboard for certificate lifetime

### ISSUE THREAD

**Issue by rugk** [mozilla/telemetry-dashboard#195]
Based [on the discussion about the 90days lifetime of Let's Encrypt certificates](https://community.letsencrypt.org/t/maximum-and-minimum-certificate-lifetimes/264) [a blog post was made](https://letsencrypt.org/2015/11/09/why-90-days.html) claiming that 29% of TLS transactions already use ninety-day certificates according to Firefox Telemetry.
However on https://telemetry.mozilla.org/ I could not find any statistics about the certificate lifetime, so I assume this information was evaluated internally.

However - for a analysis by everyone - would you mind creating a public dashboard which shows the certificate lifetime?
So that this information can be verified by anyone.

**Comment by vdjeric** [comment]
I don't know how that 29% statistic was obtained, but I doubt it was internal. 
All our histograms probes are listed on the public dash, and alternately here http://mxr.mozilla.org/mozilla-central/source/toolkit/components/telemetry/Histograms.json
Could it be the SSL_OBSERVED_END_ENTITY_CERTIFICATE_LIFETIME probe? You can see it in the dash: http://mzl.la/1MTpqc3

**Comment by vdjeric** [comment]
Note the above link is for Telemetry collected from Firefox Beta 43. It doesn't look like this probe has reached Release-channel yet. Even if it had, Telemetry is opt-out on pre-release versions of Firefox and opt-in on release Firefox, so data from Beta might still be more relevant.

**Comment by rugk** [comment]
> Could it be the SSL_OBSERVED_END_ENTITY_CERTIFICATE_LIFETIME probe? You can see it in the dash: http://mzl.la/1MTpqc3

Yes this looks like the right one.
However I do not really get out what the lifetime is, because if I assume the number displayed are days I'm wrong, because 105 are two years (as described below the chart) then I have 52,5 for one year, which clearly are not the number of days a year has. 

BTW CC: @bdaehlie (Hopefully that's the right user :smile: )

**Comment by vdjeric** [comment]
No, the x-axis label is "The lifetime of accepted HTTPS server certificates, in weeks, up to 2 years. Bucket 105 is all end-entity HTTPS server certificates with a lifetime > 2 years."

30.82% of samples are in bucket 12 which is roughly 3 months: (12 weeks * 7 days) = 84 days

**Comment by rugk** [comment]
Ah this are months okay. :smile: 

Thanks for helping me with this. So I think this issue can be considered closed.

**Comment by rugk** [comment]
Okay, just another question. How is this data collected? Does it count every single TLS connection (so certificates of websites with many css/js/... files are more represented in the statistic?) or does it only count a certificate once or how does it work?

**Comment by vdjeric** [comment]
I don't know, but you can grep Firefox source for the probe name to see what it does, or you can do an experiment using Beta Firefox and check the local result in your about:telemetry page.

https://dxr.mozilla.org/mozilla-central/source/security/manager/ssl/SSLServerCertVerification.cpp#1186

**Comment by rugk** [comment]
Okay, thanks.

**Comment by rugk** [comment]
BTW I think the one comment in the source you linked already answers my question quite good:
```c++
// Gathers telemetry on which CA is the root of a given cert chain.
// If the root is a built-in root, then the telemetry makes a count
// by root.  Roots that are not built-in are counted in one bin.
```
