### ISSUE TITLE
All Firefox versions together

### ISSUE THREAD

**Issue by rugk** [mozilla/telemetry-dashboard#197]
Why can't we also just show the statistics for all Firefox versions together? This would allow showing some basic statistics, which should not be version-dependent.

The same applies the application part (the one with Firefox Desktop and Firefox Mobile).

**Comment by chutten** [comment]
@rugk, Do you mean something like so? http://mzl.la/1HkF8MS

**Comment by rugk** [comment]
No it sill only shows the data from FF aurora 44. I'd like to see it of all FF versions where data is available
![telemetryversion](https://cloud.githubusercontent.com/assets/11966684/11378192/4ee29f70-92ea-11e5-9dfe-ee18289cf575.PNG)
.

**Comment by chutten** [comment]
Ah, my apologies, I thought you meant across all applications (Firefox Desktop, Firefox Mobile).

May I ask what you're trying to analyze with this data? The data t.m.o uses is aggregated by channel so that when you use it to perform comparisons you are acting on populations that are most similar. This allows for results that are stronger, statistically speaking.

You can get an evolution plot within a channel to show how the recorded values have changed over time, if that was your goal: http://mzl.la/1R4WlfA

**Comment by rugk** [comment]
> You can get an evolution plot within a channel to show how the recorded values have changed over time, if that was your goal: http://mzl.la/1R4WlfA

No.

> Ah, my apologies, I thought you meant across all applications (Firefox Desktop, Firefox Mobile).

No problem. I could have explained it a bit more. :smiley: 

> May I ask what you're trying to analyze with this data? The data t.m.o uses is aggregated by channel so that when you use it to perform comparisons you are acting on populations that are most similar. This allows for results that are stronger, statistically speaking.

Well... this is what data I want: https://github.com/mozilla/telemetry-dashboard/issues/195
And IMHO there it does not really matter which version of FF collected this data as it is not about a Firefox-internal thing, but more like a web statistic. And I think to have more samples there would be nice in this case.

**Comment by chutten** [comment]
Now I understand, thank you for your patience. You want to know for a particular day's Internet (say, last Tuesday) the distribution of TLS certificate ages, as observed by Firefox.

t.m.o's existing dashboards won't be able to do this for you. But you could write one yourself using [telemetry.js](https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/v2/doc.md).

Here's how I'd do it:
```js
Telemetry.init(() => {
  // collect all the channels and versions
  var _versions = {};
  Telemetry.getVersions()
    .sort()
    .reverse() // you probably don't need to sort these, I adapted this from elsewhere
    .map(versionString => {
      var [channel, version] = versionString.split('/');
      if (!_versions[channel]) {
        _versions[channel] = [version];
      } else {
        _versions[channel].push(version);
      }
    });

  // collect and combine all of the data we're interested in
  var combinedEvo;
  for (var channel in _versions) {
    _versions[channel].forEach(version => {
      Telemetry.getEvolution(channel, version, 'SSL_OBSERVED_END_ENTITY_CERTIFICATE_LIFETIME', {} /*filters*/, true /*useSubmissionDate*/, evoMap => {
        var evo = evoMap[''].dateRange(new Date('2015-11-17'), new Date('2015-11-17')).sanitized();
        if (!combinedEvo) {
          combinedEvo = evo;
        } else {
          combinedEvo.combine(evo);
        }
      });
    });
  }
});
```

Throw a counter or a Promise on that so you know when it's done async-ing its way through all of those getEvolution calls, and you have yourself an Evolution instance with the combined data of all of the submissions received last Tuesday.

Then you find the bucket that contains the value you want...
```js
var histogram = combinedEvo.histogram();
var bucketIndex = histogram.buckets.findIndex((el, index) =>
  el <= WEEKS_IN_THREE_MONTHS && WEEKS_IN_THREE_MONTHS <= histogram.buckets[Math.min(histogram.buckets.length - 1, index + 1)]);
```

Then the number of samples in that bucket is
```js
var threeMonthSamples = histogram.data[bucketIndex];
```

And the percentage of the population that represents is
```js
var percentage = threeMonthSamples / histogram.count * 100;
```

Is this helpful?

**Comment by rugk** [comment]
Thanks for the detailed reply. I will look into it.

However:
> You want to know for a particular day's Internet (say, last Tuesday)

Ehm, no, not really. I mean I could, but it does not really matter. It could just use all data it has (from all versions and from all relevant FF versions). I just want to have some good statistics.
But as I see in your code I may just change the date and it should be fine.

**Comment by chutten** [comment]
It could very well be that 3month certs are a new and rising trend, so I'd recommend taking a snapshot view rather than trying to aggregate over all connections over all time. There are plenty of submissions for each histogram, so you probably don't need to grab more than a day's worth. Just be sure to choose nothing more recent than, say, a couple days back as it takes some time for submissions to trickle in.

Glad to be of service!

**Comment by rugk** [comment]
Okay, also a view how you can see this.
And thanks for the support. I'll close this issue as I do not think you want to add support for filtering "all FF versions" in the official dashboard. If anyone things something different this issue may be reopened of course.
