### ISSUE TITLE
Unable to view telemetry histograms for CHECKERBOARDED_CSSPIXELS_MS

### ISSUE THREAD

**Issue by staktrace** [mozilla/telemetry-dashboard#203]
I filed this as https://bugzilla.mozilla.org/show_bug.cgi?id=1229488, copying from there:

STR:
1. Go to https://telemetry.mozilla.org/
2. Click on "Histogram dashboard". This will load the GC_MS histogram for desktop by default. Wait for it to finish loading
3. Click on GC_MS and change the measure to CHECKERBOARDED_CSSPIXELS_MS

Expected:
Shows histogram data for CHECKERBOARDED_CSSPIXELS_MS

Actual:
The GC_MS chart disappears, but the "Time spent running JS GC (ms)" label remains. No new chart appears. The web console has this error:

TypeError: histograms[0] is undefined       dist.js:992:3

**Comment by chutten** [comment]
Running the same parameters through the [dashboard generator](https://telemetry.mozilla.org/dashboard-generator/index.html?channel=nightly&version=&metric=CHECKERBOARDED_CSSPIXELS_MS&useSubmissionDate=false&sanitize=false&trim=false&compare=&sensibleCompare=true&evoVersions=0&filters=) shows a better error message "No data to graph"

@staktrace, Is it possible that there actually is no data?

**Comment by staktrace** [comment]
It's possible, but I hope that's not the case. I added the histogram about two weeks ago (bug 1221694) and I verified that in my own desktop nightly build about:telemetry shows some data for this histogram, so it should be working. Do you know how long it takes for the data to be gathered?

**Comment by chutten** [comment]
Looking at an evolution over submission dates for nightly/45 GC_MS, the latest submissions pulled from the aggregator are from November 28.

You could try running a custom analysis on a spark cluster. It has access to un-aggregated data: https://analysis.telemetry.mozilla.org/

**Comment by vitillo** [comment]
See [Bug 1229738](https://bugzilla.mozilla.org/show_bug.cgi?id=1229738) for why the latest submissions are from November 29th of November.

**Comment by staktrace** [comment]
Thanks for the info! If I find some time I'll try the spark cluster thing but otherwise I might just wait it out.
