### ISSUE TITLE
sanitize flag is ignored?

### ISSUE THREAD

**Issue by ghost** [mozilla/telemetry-dashboard#218]
Generate the dashboard from this: https://telemetry.mozilla.org/dashboard-generator/index.html?channel=beta&version=&metric=GFX_CRASH&useSubmissionDate=false&sanitize=false&trim=true&compare=&sensibleCompare=true&evoVersions=1&filters=

The plots variable (in JS codepen) shows "sanitize": false, as expected, but where the graph should be, I get this instead - note "sanitize": true in there:

All data sanitized away
{
  "channel": "beta",
  "version": "44",
  "metric": "GFX_CRASH",
  "useSubmissionDate": false,
  "sanitize": true,
  "evoVersions": "1",
  "filters": {},
  "trim": true,
  "sensibleCompare": true,
  "keyLimit": 4
}

**Comment by chutten** [comment]
Odd, for me generating the dash works from that link. It's a flat, mostly-empty graph.

**Comment by mozilla-milan** [comment]
Interesting, I do now see an empty chart.  Still not what I see here: https://telemetry.mozilla.org/new-pipeline/evo.html#!aggregates=bucket-0&cumulative=0&end_date=2016-01-18&keys=!__none__!__none__&max_channel_version=beta%252F44&measure=GFX_CRASH&min_channel_version=beta%252F44&product=Firefox&sanitize=0&sort_keys=submissions&start_date=2015-12-17&trim=1&use_submission_date=1, but at least I see the chart, not the data.

**Comment by chutten** [comment]
To me they look nearly identical except for the cosmetic choices (on dashgen the x axis ticks don't extend all the way up, the date format is different, the colour choices are deliberate...)
![dashgennodata](https://cloud.githubusercontent.com/assets/1123376/12519401/840f261e-c10c-11e5-9e3c-d7592b1dae54.PNG)
![dashnodata](https://cloud.githubusercontent.com/assets/1123376/12519402/841d019e-c10c-11e5-97ae-5d28bf9fbcdb.PNG)

**Comment by mozilla-milan** [comment]
The graph below that one is what I'm looking for.
<img width="1330" alt="screen shot 2016-01-22 at 13 33 28" src="https://cloud.githubusercontent.com/assets/2856482/12519442/d05c2fb2-c10c-11e5-9e52-144e6986d115.png">

**Comment by chutten** [comment]
Oh, you want the graph of the number of submissions per day? Dashgen presently doesn't support this kind of graph. It probably wouldn't be too hard to add the capability (add the necessary parameters and plotting code to telemetry-wrapper.js, expose it via dashgen as a third choice (histogram, evolution, submissions)... it'd be a bit of work)

Why are you interested in the number of users per day who sent pings with payloads that contain the GFX_CRASH histogram in it? It sounds as though you may prefer [crash-stats](https://crash-stats.mozilla.com/) to answer the questions you are asking (though I don't know what questions those are, so I'm really only guessing :S )

**Comment by mozilla-milan** [comment]
Aah, that's good to know.  So, yes, I want the daily pings, and it sounds like that isn't quite there yet.  That's OK, I can just look at the standard telemetry page to look for it.

And, yes, these are counting the "avoided crashes", so I want to look at them as if they were crash reports.

**Comment by chutten** [comment]
You could write your own analysis to get exactly what you want using analysis.telemetry.mozilla.org. The "Telemetry Hello World.ipynb" that comes with each ad-hoc cluster is a really good starting point since it is looking at the data in a similar way to how your analysis would. There are also plenty of people on #telemetry and #perf that would be willing to help if you get stuck.
