### ISSUE TITLE
SunOS is missing from OS selection

### ISSUE THREAD

**Issue by jeffpc** [mozilla/telemetry-dashboard#222]
Illumos-derived distros (and Solaris) which identify as SunOS don't appear in the OS selection list.

E.g., my user agent string is:

```
Mozilla/5.0 (X11; SunOS i86pc; rv:44.0) Gecko/20100101 Firefox/44.0
```

I'm running on a x86 PC-style hw (i86pc), and my OS is the illumos-derived OpenIndiana (SunOS).

**Comment by chutten** [comment]
Ah, that is likely because the SunOS build is not "Official".

If your Firefox is not built with `MOZILLA_OFFICIAL=1` then it will not ever report Telemetry. I know that builds released on mozilla.com are official, but I assume the builds constructed for SunOS aren't.

**Comment by jeffpc** [comment]
Ah, I didn't realize that the telemetry is only mean for official builds.

It turns out that OpenIndiana Hipster's firefox is compiled with MOZILLA_OFFICIAL=1.  So, as far as I can tell (about:telemetry), my browser should be attempting to submit telemetry data.

**Comment by chutten** [comment]
Hm. Well, let's start first by double-checking that you are submitting the data you ought to be.

To get the raw data that you are submitting, visit `about:healthreport`. Click on "Raw Data" at the top, and then click on a recent ping. This will show a mess of JSON.

Search on the page for "os", and paste that structure here in the Issue (should have "name", "version", and some other stuff)

**Comment by georgf** [comment]
Telemetry also requires MOZ_TELEMETRY_REPORTING to be defined.
I think we only want to report Telemetry for our officially provided builds (and partner repacks) though.
@bsmedberg, can you confirm?

**Comment by chutten** [comment]
If we'd like to enable telemetry on SunOS' builds of Firefox, the bugs under https://bugzilla.mozilla.org/show_bug.cgi?id=1352981 are a good starting place for how-to.
