### ISSUE TITLE
Requesting some histograms overflows date range

### ISSUE THREAD

**Issue by bifurcation** [mozilla/telemetry-dashboard#242]
When using telemetry.js, requesting a histogram evolution will request it over the entire date range when the histogram has been active.  The date range is encoded as a list of dates in a URL sent in a GET request to `https://aggregates.telemetry.mozilla.org/`.  For example, the following pages both call `Telemetry.getEvolution(channel, version, MEASURE, {}, true, callback)` and get this overflow:
- [PKI league table](https://ipv.sx/pkilt/)
- [Time series generator](https://ipv.sx/telemetry/general-v2.html?channels=beta%20release&measure=CERT_VALIDATION_SUCCESS_BY_CA&target=52&absolute=0&relative=1)

To address this, we need to either reduce the date range sent by telemetry.js or send the date range in a way that can handle more dates (e.g., as POST parameters).

**Comment by chutten** [comment]
Can you give me the exact channel, version, and MEASURE used?

**Comment by chutten** [comment]
https://aggregates.telemetry.mozilla.org/aggregates_by/submission_date/channels/beta/dates/ returns dates for version 39 that range from 20160815 all the way back to when it was relevant in 20150708. This, summed together, exceeds the 4K request URL limit on whatever part of the infrastructure has a 4K URL limit.
