### ISSUE TITLE
Some error pages do not return Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by bifurcation** [mozilla/telemetry-dashboard#243]
When `aggregates.telemetry.mozilla.org` returns an error response (as in #242), it does not send the `Access-Control-Allow-Origin` header.  This causes errors to appear to be CORS failures, when in fact they are HTTP errors.  The server should emit the ACAO header so that the proper error messages appear in the developer console.

**Comment by chutten** [comment]
Refiled over [yonder](https://github.com/mozilla/python_mozaggregator/issues/18)
