### ISSUE TITLE
Data disappears after closing and restoring a tab

### ISSUE THREAD

**Issue by gijsk** [mozilla/telemetry-dashboard#249]
1. open https://telemetry.mozilla.org/new-pipeline/dist.html#!arch=&cumulative=0&e10s=&end_date=2016-09-26&keys=__none__!__none__!__none__!__none__&max_channel_version=beta%252F50&measure=FX_STARTUP_MIGRATION_AUTOMATED_IMPORT_UNDO&min_channel_version=null&os=&processType=&product=&sanitize=0&sort_keys=submissions&start_date=2016-09-20&table=0&trim=0&use_submission_date=0
2. wait for it to load, then in the measure/histogram dropdown select FX_STARTUP_MIGRATION_UNDO_REASON
3. wait for that to load, close tab
4. then accel-shift-t to "undo close tab"

Expected: see the same data as before reopening

Actual: "No data matches these filters and settings."

If you copy the new URL and load in a new tab, everything works fine (and there is definitely for sure data).

Apparently this reproduces in Firefox Beta, as well as Nightly, but not Google Chrome.

**Comment by chutten** [comment]
It's fixed!
