### ISSUE TITLE
Improve security of telemetry

### ISSUE THREAD

**Issue by april** [mozilla/telemetry-dashboard#250]
Hello hello!  It's your friendly neighborhood infosec engineer, April!

I was hoping we could make some improvements to the security of telemetry.mozilla.org and analysis.telemetry.mozilla.org, especially as they are both on our bug bounty list.

A few things should probably be (hopefully) relatively simple:

```
Strict-Transport-Security: max-age=63072000
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
```

HSTS helps ensure that users only visit the site over HTTPS, XCTO disables browser MIME type sniffing, and XFO: DENY blocks framing.  If framing is needed by the same origin, `SAMEORIGIN` works instead of `DENY`.  If specific sites need to frame telemetry, then using CSP's `frame-ancestors` directive is probably the way to go.

Speaking of CSP, I'd like to get CSP going on telemetry as well.  This can significantly decrease the rate of cross-site scripting issues, a large part of our bug bounty payouts.

I've gotten a start on the CSP for telemetry.mozilla.org; there are a lot of inline scripts that will need to be moved to a separate JS file, but once that is done hopefully something like this will work:

```
Content-Security-Policy: default-src 'none'; connect-src https://aggregates.telemetry.mozilla.org; font-src https://maxcdn.bootstrapcdn.com; img-src 'self'; script-src 'self' https://cdnjs.cloudflare.com/ajax/libs/moment.js/ https://cdnjs.cloudflare.com/ajax/libs/d3/ https://cdnjs.cloudflare.com/ajax/libs/jqueryui/ https://code.jquery.com https://maxcdn.bootstrapcdn.com; style-src 'self' 'unsafe-inline' https://maxcdn.bootstrapcdn.com
```

For API sites (that is, ones that only return application/json), a simple CSP as such can be used:
`Content-Security-Policy: default-src 'none'; frame-ancestors 'none'`

Thanks so much!  Please let me know if you have any questions!

**Comment by chutten** [comment]
The bugzilla version of this is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1307835
