### ISSUE TITLE
TMO Resets Probe

### ISSUE THREAD

**Issue by fbertsch** [mozilla/telemetry-dashboard#254]
If the new Firefox version does not have data for the currently selected probe, TMO resets the view to the first probe in the list

**Comment by chutten** [comment]
What would make more sense?

**Comment by fbertsch** [comment]
Probably a message that says "No data available"?

**Comment by himanish-star** [comment]
@chutten , Can I take over this issue along with my work in PR #381

**Comment by chutten** [comment]
Sure! You may wish to ask fbertsch for steps to reproduce his issue.

**Comment by himanish-star** [comment]
Thanks for assigning this to me

**Comment by himanish-star** [comment]
@fbertsch , could you please explain the steps to reproduce this issue.

**Comment by himanish-star** [comment]
@fbertsch, Please explain the steps to reproduce this issue

**Comment by chutten** [comment]
I feel it pertinent to mention that @fbertsch is away from work this week. He'll not be able to get to this until Monday at the soonest.

**Comment by himanish-star** [comment]
Ok, no problem I'll wait

**Comment by fbertsch** [comment]
Well I can't seem to reproduce this in any way, shape, or form. We'll close it unless someone runs in to it again.
