### ISSUE TITLE
https://telemetry.mozilla.org/crashes/office-dashboard.html is using M+C-S for Nightly, M+C for Aurora

### ISSUE THREAD

**Issue by marco-c** [mozilla/telemetry-dashboard#260]
`content_shutdown_crashes` is missing from https://sql.telemetry.mozilla.org/queries/199, but is present in https://sql.telemetry.mozilla.org/queries/200, so for Nightly the dashboard is going to show M+C-S, for Aurora M+C.

There's probably just a typo in the query (`content_shutdown_crashes` missing from one of the SELECTs).

The legend at the top should be updated too (it says `App crashes - main+content`).

**Comment by chutten** [comment]
The office dashboard has been replaced, so this is no longer something we need to worry about. Yay!
