### ISSUE TITLE
Dates and buildIDs seem dependant upon the viewers timezone.

### ISSUE THREAD

**Issue by mikeconley** [mozilla/telemetry-dashboard#265]
STR:

1) Switch your timezone on your local machine to Central European Standard Time (I chose "Spain" in OS X)
2) Visit https://mzl.la/2fME2x2
3) Notice the regression in the 95th percentile on that graph. Note that the regression allegedly appears on Nov 6th, 2016, and that the associated build ID is 20161106
4) Switch your timezone to Eastern Standard Time
5) Reload https://mzl.la/2fME2x2
6) Notice that the spike now appears to have occurred on Nov 5th, 2016, and that the associated build ID is 20161105.

This is very strange. The X-axis is supposed to be the date derived by the buildID of the submitted ping, which has nothing to do with my timezone.

Because of this inconsistency, I have no idea where this regression was introduced - in the build on the 5th, or the build of the 6th?

**Comment by mikeconley** [comment]
Here's another example.

1. Switch your timezone to Central European Time.
2. Visit https://mzl.la/2fN0AxM
3. Notice that the very first build ID that the ping shows up in is 20161106
4. Switch your timezone to Eastern Standard Time
5. Reload https://mzl.la/2fN0AxM
6. Notice that the very first build ID that the ping shows up in is 20161105 instead.

I'll note that this probe only started being written to in the 20161106 build, so the "Central European Time" view is correct.

**Comment by chutten** [comment]
Fixed!
