### ISSUE TITLE
Show statistics with percentiles and median while comparing

### ISSUE THREAD

**Issue by digitarald** [mozilla/telemetry-dashboard#274]
The interface has a summary with percentiles and median when showing a single histogram. These numbers would be useful when comparing histograms, but right now the space is left empty.

**Comment by bani** [comment]
I decided to take a stab at this one as an attempt to contribute to this project.

I started with just the Median, as it may become too cluttered to add all percentiles when there is a large number of segments.

You can take a look at [this example on my fork](http://baniverso.com/telemetry-dashboard/new-pipeline/dist.html#!compare=os&cumulative=0&end_date=2017-12-19&keys=__none__!__none__!__none__&max_channel_version=nightly%252F59&measure=GC_MS&min_channel_version=null&processType=*&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2017-11-13&table=0&trim=1&use_submission_date=0). Is this what you had in mind?

I'm leaving the order as is (apparently it's alphabetical), but maybe it'd be better to sort by the number. What do you think, is it worth the extra computation?

**Comment by chutten** [comment]
That's pretty good, @bani!

I'm not sure if sorting would be better or worse. All else fails, leave it as it is now and take the sorting question to a follow-up issue.

Now it's just a matter of trying to figure out how to fit the rest of the aggregates in that space...

What do you think about a tabular view with five columns (5th, 25th, median, 75th, 95th) and one row per compare value? It might be one way to fit all the information into the space we have, especially when [comparing many values](https://bit.ly/2DnyhCj).

**Comment by bani** [comment]
Updated to a table.
I had to decrease the font size to fit in the div. Otherwise it was sort of ok, but with a smaller window the scrollbar would cover the 95th percentile column.

**Comment by chutten** [comment]
(Sorry for the delayed response. Just returned from end-of-year holidays)

Smaller window widths are always problematic in the current design. It doesn't relayout properly on narrow screens until it already cuts off quite a bit of content... and that's the current state :S

I wouldn't worry about it too much. We can tackle the problem of narrow-ish windows another time. (You can file an Issue and start working on it right away, if you'd like!)

I'm happy to review it as it is, if you prefer the smaller font size. Or you can return it to the original, your choice.
