### ISSUE TITLE
Stability dashboard lacks defined upper and lower tolerance bounds

### ISSUE THREAD

**Issue by ddurst** [mozilla/telemetry-dashboard#276]
In https://telemetry.mozilla.org/crashes/, the colors should be indicated the status of that data (green = OK, yellow = potential issue, red = needs attention). Those colors -- and the values that trigger them -- were originally pulled from https://arewestableyet.com/ (which appears to not have set them regularly or based them on anything immutable).

We need a concrete upper and lower bound from relman for these.

**Comment by chutten** [comment]
Migrated: https://bugzilla.mozilla.org/show_bug.cgi?id=1381873
