### ISSUE TITLE
Stability Dashboard should use latest released version, not most popular

### ISSUE THREAD

**Issue by chutten** [mozilla/telemetry-dashboard#281]
[Presently](https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/crashes/index.html#L106) the code checks for the most popular release by number of kilo usage hours.

It would be far more relevant to relman and uptime to see the figures for the latest release, even if it does cause the kuh plot to dip on merge day.

**Comment by ddurst** [comment]
Can we just toggle between the two?

**Comment by chutten** [comment]
Why? Do you know of anyone who would prefer to look at an older-than-current version?

**Comment by ddurst** [comment]
Nevermind! I misread this.

**Comment by chutten** [comment]
Live preview can be found here: https://chutten.github.io/telemetry-dashboard/crashes/
