### ISSUE TITLE
Remove "M+C" from the dashboard in favor of "C" or "C-S"

### ISSUE THREAD

**Issue by philipp-sumo** [mozilla/telemetry-dashboard#290]
this is an enhancement request: 
the telemetry-fed crash dashboard at https://telemetry.mozilla.org/crashes/ lists a "Main (M)" crash rate for crashes in the browser process. it would be helpful if we could have a dedicated rate that shows the ups/down just for content crashes as well.

**Comment by chutten** [comment]
Give it a go now? How's it look?

**Comment by philipp-sumo** [comment]
looking great, thank you!
