### ISSUE TITLE
TMO doesn't show data for expired/removed probes

### ISSUE THREAD

**Issue by staktrace** [mozilla/telemetry-dashboard#294]
The SCROLL_LINKED_EFFECT_FOUND probe was removed a few releases ago (it was a valid unexpired probe in Firefox 49 nightly, for example). And in the TMO interface, I can pick Firefox 49 from the histogram view, and then pick SCROLL_LINKED_EFFECT_FOUND from the list of probes. However no data shows up. There definitely *was* data associated with this probe and it would be great if it didn't disappear after the probe expiry.

**Comment by chutten** [comment]
Here's a link: https://mzl.la/2mJHuwe

[Here's](https://aggregates.telemetry.mozilla.org/aggregates_by/submission_date/channels/release/?version=49&dates=20170228,20170227,20170226,20170225,20170224,20170223,20170222,20170221,20170220,20170219,20170218,20170217,20170216,20170215,20170214,20170213,20170212,20170211,20170210,20170209,20170208,20170207,20170206,20170205,20170204,20170203,20170202,20170201,20170131,20170130,20170129,20170128,20170127,20170126,20170125,20170124,20170123,20170122,20170121,20170120,20170119,20170118,20170117,20170116,20170115,20170114,20170113,20170112,20170111,20170110,20170109,20170108,20170107,20170106,20170105,20170104,20170103,20170102,20170101,20161231,20161230,20161229,20161228,20161227,20161226,20161225,20161224,20161223,20161222,20161221,20161220,20161219,20161218,20161217,20161216,20161215,20161214,20161213,20161212,20161211,20161210,20161209,20161208,20161207,20161206,20161205,20161204,20161203,20161202,20161201,20161130,20161129,20161128,20161127,20161126,20161125,20161124,20161123,20161122,20161121,20161120,20161119,20161118,20161117,20161116,20161115,20161114,20161113,20161112,20161111,20161110,20161109,20161108,20161107,20161106,20161105,20161104,20161103,20161102,20161101,20161031,20161030,20161029,20161028,20161027,20161026,20161025,20161024,20161023,20161022,20161021,20161020,20161019,20161018,20161017,20161016,20161015,20161014,20161013,20161012,20161011,20161010,20161009,20161008,20161007,20161006,20161005,20161004,20161003,20161002,20161001,20160930,20160929,20160928,20160927,20160926,20160925,20160924,20160923,20160922,20160921,20160920,20160919,20160918,20160917,20160916,20160915,20160914,20160913,20160912,20160911,20160910,20160909,20160908,20160907,20160906,20160902,20160830,20160829,20160823,20160822,20160816,20160815,20160811,20160810,20160809,20160808,20160804,20160803,20160802,20160801,20160726,20160725,20160724,20160723,20160722,20160721,20160720,20160719,20160718,20160717,20160716,20160715,20160714,20160713,20160711,20160710,20160709,20160707,20160706,20160705,20160704,20160703,20160702,20160701,20160630,20160629,20160628,20160627,20160624,20160623,20160622,20160621,20160620,20160619,20160618,20160617,20160616,20160610,20160607,20160603&metric=SCROLL_LINKED_EFFECT_FOUND&application=Firefox) how it's trying to get its data. (it 404s)

To the best of my knowledge we should have historical aggregates. @fbertsch your thoughts?

**Comment by fbertsch** [comment]
Yes we do. The data is there, but you can't access it, because we only use the most recent version of Histograms.json (and Scalars.yaml) to retrieve the definitions [0]. Thus if they are no longer in there, they are ignored (and you get a 404).

Basically, our thought process was "if it's expired, no one really cares about it anyways". I'm willing to revisit that assumption, but it would take some work to update the code to retrieve historical Histograms.json files.

[0] https://github.com/mozilla/python_mozaggregator/blob/master/mozaggregator/service.py#L236

**Comment by chutten** [comment]
Worthy work, I should think, as without such a change we're persisting historical data in a way that is inaccessible. 

Also, it might act as a disincentive for people to collect data for a controlled period of time, cleaning up Histograms.json as they go.

**Comment by fbertsch** [comment]
Agreed. I'll put in a bug.

**Comment by fbertsch** [comment]
Made bug 1344280 for this.

**Comment by fbertsch** [comment]
Closing this since this is an issue with python_mozaggregator and not the TMO frontend.
