### ISSUE TITLE
Enable GA

### ISSUE THREAD

**Issue by fbertsch** [mozilla/telemetry-dashboard#300]
We would like to have GA on every dash in TMO. This can help us decide how things are used (which dashboards) and how much.

**Comment by geekodour** [comment]
implementing GA on each page, does that mean having pageviews on each page from GA? or something more?
api link: https://developers.google.com/analytics/devguides/collection/analyticsjs/pages
api link for spa: https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications
It can be placed here, if it's meant to be on the users side.
![](http://i.imgur.com/Rjc91BJ.png "It can be placed here")

**Comment by fbertsch** [comment]
We really just want pageviews on each page from GA. We could potentially include more information (such as: probe selection in Evolution/Measurement view), but we'll start simple and add what we need later.

**Comment by geekodour** [comment]
hmm, is this an internal project? seems like to some work with api credentials would be involved if not much. let me know if I could help in any small way with this issue.

**Comment by chutten** [comment]
Also being tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1293750

**Comment by chutten** [comment]
Closing so further discussion can be had in bugzilla
