### ISSUE TITLE
links are not backward compatible

### ISSUE THREAD

**Issue by hmntptwl** [mozilla/telemetry-dashboard#303]
@chutten
The two links mentioned  [here](https://github.com/hemant1612/telemetry-dashboard/blob/hhhh1612/advanced/index.html#L259)
- [telemetry.mozilla.org/v1/big.js ](https://telemetry.mozilla.org/v1/big.js ) 
- [telemetry.mozilla.org/v1/telemetry.js](https://telemetry.mozilla.org/v1/telemetry.js) 

are not active to be used for local deployment

**Comment by chutten** [comment]
This is because telemetry.js v1 has been deprecated in favour of telemetry.js v2. It is entirely possible that anything under advanced/ might not work.
