### ISSUE TITLE
Stability dahsboard shows arbitrary Nighly versions

### ISSUE THREAD

**Issue by philipp-sumo** [mozilla/telemetry-dashboard#307]
In the past few days, the https://telemetry.mozilla.org/crashes/ dashboard shows data for arbitrary nightly versions and not the latest 55.0a1 (it's also happening with aurora, but we shouldn't care about that anymore - issue #306).

it's displaying the following versions if i look at the dashboard currently:
2017-05-01: 54.0a1
2017-04-30: 45.0a1
2017-04-29: 48.0a1
2017-04-28: 48.0a1
...
apparently the issue started at 2017-04-19

**Comment by chutten** [comment]
Fixed by removing aurora. Apparently it was playing havoc wider than just its own channel :S

**Comment by philipp-sumo** [comment]
thanks for the quick fix!
