### ISSUE TITLE
alerts.tmo doesn't load

### ISSUE THREAD

**Issue by staktrace** [mozilla/telemetry-dashboard#311]
I got a telemetry regression email with this link:

http://alerts.telemetry.mozilla.org/index.html#/detectors/1/metrics/2195/alerts/?from=2017-05-12&to=2017-05-12

It doesn't load in the browser. The web console shows some JS errors about `navigator.id` not being defined, maybe that's causing important scripts to abort?

**Comment by chutten** [comment]
I was triaging telemetry-alerts yesterday and it was working. Today it isn't. I didn't update my browser in the interim.

This is concerning.

**Comment by chutten** [comment]
I see https://bugzilla.mozilla.org/show_bug.cgi?id=1014608 which points the finger at extensions, but this happens even with a fresh profile.

**Comment by chutten** [comment]
Oh no.  I wonder if this is Persona.

**Comment by chutten** [comment]
Yup, it was Persona. Should be all fixed now in mozilla/medusa
