### ISSUE TITLE
Evolution View should have a way to see "Total Histogram Count"

### ISSUE THREAD

**Issue by fbertsch** [mozilla/telemetry-dashboard#312]
We currently have "Number of Pings" with the label "Daily Metric Count". I would prefer to have to plots with "counts":
1. "Daily Ping Count" - number of pings received in that day with that metric
2. "Daily Metric Count" - number of instances of that metric recieved per day.

**Comment by ab0092** [comment]
May i get some more details on this issue ? I would like to work on this.

**Comment by fbertsch** [comment]
@ab0092, we did get the change for showing `daily ping count` in #330.

What we need now is another plot (in the evolution view) that will look very similar to the one that shows "Daily Ping Count" [0]. Instead of showing number of pings, it will show number of instances of a measurement we've seen. Let me explain a bit more.

When we receive a Firefox Ping, it has histograms in the following form: `{value1: count1, value2: count2, ... valueN: countN}`. For example, it might be `{1: 10, 2:1}`, in which case that single ping is reporting 10 instances of 1, and 1 instance of 2. "Daily Ping Count" is just reporting the number of pings seen; in addition, we want another plot below it that reports "Daily Metric Count", which (for our example ping `{1: 10, 2:1}`) would be 11.

[0] https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/new-pipeline/src/evo.js#L892

**Comment by adrian17** [comment]
@ab0092, are you working on this bug? If not, I can take a shot at this.

**Comment by ab0092** [comment]
@adrian17 i have not yet started working in this issue so you can work on it, i will look into the other issues to work on. :-)
