### ISSUE TITLE
Please, bring back some kind of Slow SQL dashboard

### ISSUE THREAD

**Issue by mak77** [mozilla/telemetry-dashboard#313]
I constantly feel the lack of this dashboard, I used to look at it to prioritize work on Storage and its consumers (Places, cookies, form history, dom storage...), but it's gone from a long time. I tried for some time to understand if we could live without this, but I constantly lack data.
We don't need to retain everything, even just having the top 10 offenders on and off main-thread would be great, or showing queries over a certain time threshold (> 100ms). This was one of the best tools to identify queries that we consider fine but are instead very slow in the wild.

**Comment by bsmedberg** [comment]
Marco, you need to work with the data engineering team on this (in bugzilla, not here). Please contact kparlante and thuelbert to get things started. That team will need a fairly detailed specification of how the incoming data should be transformed into the results you need. I suspect a batch report would be a simpler/faster way to solve this than a dashboard, but they can help you decide that.

**Comment by mreid-moz** [comment]
@mak77 please ni? me on said bug when it gets filed and I can add the old analysis code for reference.
