### ISSUE TITLE
Evolution dashboard fails to load.

### ISSUE THREAD

**Issue by farre** [mozilla/telemetry-dashboard#326]
Loading the evolution dashboard fails due to Content Security Policy errors:

Firefox Nightly 57.0a1 (2017-08-03) (64-bit) on Ubuntu

Loading failed for the <script> with source “https://code.jquery.com/jquery-1.11.3.min.js”. evo.html:108
Loading failed for the <script> with source “https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js”. evo.html:109
Loading failed for the <script> with source “https://telemetry.mozilla.org/new-pipeline/lib/bootstrap-multiselect.js”. evo.html:110
Loading failed for the <script> with source “https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js”. evo.html:111
Loading failed for the <script> with source “https://telemetry.mozilla.org/new-pipeline/lib/daterangepicker.js”. evo.html:112
Loading failed for the <script> with source “https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js”. evo.html:115
Loading failed for the <script> with source “https://telemetry.mozilla.org/new-pipeline/lib/metricsgraphics.js”. evo.html:116
Loading failed for the <script> with source “https://telemetry.mozilla.org/v2/telemetry.js”. evo.html:118
Loading failed for the <script> with source “https://telemetry.mozilla.org/new-pipeline/src/dashboards.js”. evo.html:119
Loading failed for the <script> with source “https://telemetry.mozilla.org/new-pipeline/src/evo.js”. evo.html:120
Content Security Policy: The page’s settings blocked the loading of a resource at https://code.jquery.com/jquery-1.11.3.min.js (“script-src 'none'”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js (“script-src 'none'”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://telemetry.mozilla.org/new-pipeline/lib/bootstrap-multiselect.js (“script-src 'none'”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js (“script-src 'none'”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://telemetry.mozilla.org/new-pipeline/lib/daterangepicker.js (“script-src 'none'”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js (“script-src 'none'”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://telemetry.mozilla.org/new-pipeline/lib/metricsgraphics.js (“script-src 'none'”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://telemetry.mozilla.org/v2/telemetry.js (“script-src 'none'”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://telemetry.mozilla.org/new-pipeline/src/dashboards.js (“script-src 'none'”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://telemetry.mozilla.org/new-pipeline/src/evo.js (“script-src 'none'”).

![screenshot](https://user-images.githubusercontent.com/776258/29315036-3e67f2ea-81c1-11e7-8f19-cac6c36c3111.png)

**Comment by chutten** [comment]
Works for me. Would one of your addons be enforcing a rather more strict policy of cross-site script inclusion than tmo does natively?

**Comment by chutten** [comment]
Rather more specifically, to my knowledge we do not set script-src: none in CSP headers or meta on TMO (our CSP is rather lax at the moment. https://bugzilla.mozilla.org/show_bug.cgi?id=1307835 is for improving it)

**Comment by farre** [comment]
Took a look at the headers, and at least evo.html sets the CSP header.
![screenshot2](https://user-images.githubusercontent.com/776258/29356764-9d974bbc-8275-11e7-89e0-a019ba237002.png)

**Comment by farre** [comment]
On the other hand, using my own built nightly I don't get that response header. Starting to get confusing here. And I turned off all of my add-ons to be sure, and I shouldn't have any strange settings turned on either.

**Comment by farre** [comment]
And https://telemetry.mozilla.org/new-pipeline/dist.html is working just fine, it's just https://telemetry.mozilla.org/new-pipeline/evo.html that's broken for me.

**Comment by farre** [comment]
Now I'm on Firefox Nightly 57.0a1 (2017-08-20), and now it works. No CSP header either.

**Comment by chutten** [comment]
This is truly confusing. I'm not sure how I can help.

**Comment by chutten** [comment]
Probably some legacy addon that was disabled on the Aug 11 build... Closing as working for now :)
