### ISSUE TITLE
Link to the histogram simulator on the landing page

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#328]
The [histogram simulator](https://telemetry.mozilla.org/histogram-simulator/) can be pretty useful to understand bucket handling etc.
Unless there are known issues with it, we should surface it on the main page.

**Comment by ab0092** [comment]
@georgf i would like to work on this issue. Can u please assign me this issue and also provide me with some more details of what is actually required. Thanks..

**Comment by chutten** [comment]
It's yours to work on if you'd like to.

What needs to be done: Add a link and a description for the histogram simulator to the index.html in the "Other Dashboards" section, following the pattern already established in that list .

**Comment by ab0092** [comment]
@chutten i have added the Histogram Simulator in the Home/Main Page under Other DashBoards Serction. Could you check the description for the link, is that description gonna work ?

**Comment by ab0092** [comment]
The changes can be viewed at https://ab0092.github.io/telemetry-dashboard/

**Comment by chutten** [comment]
Can you submit a Pull Request? I can review the wording and the code better that way.

**Comment by ab0092** [comment]
I have made a PR. Waiting for your response.

**Comment by chutten** [comment]
https://github.com/mozilla/telemetry-dashboard/pull/336#pullrequestreview-66492624
