### ISSUE TITLE
telemetry.m.o shows data for e10s-enabled Firefox Mobile when such a configuration shouldn't exist

### ISSUE THREAD

**Issue by staktrace** [mozilla/telemetry-dashboard#329]
https://mzl.la/2xsCxAS for example, is the CONTENT_RESPONSE_DURATION histogram on 57 nightly for Firefox Mobile with e10s enabled. It shows around 1.65M samples. The thing is, Firefox Mobile (which I believe to be Fennec) doesn't work with e10s enabled. So something is weird here. If I filter the data by process, only the parent process shows up as having any data. Maybe whatever the telemetry code is using to check for e10s-ness is not correct on Android?

/cc @snorp

**Comment by fbertsch** [comment]
Take a look at https://mzl.la/2wVZ8UY. Note the second plot (Daily Metric Count) shows number of pings received per day. It's showing 200-300, so a pretty low number. It did jump up around during 56, however.

The code to determine if e10s is enabled is [here](https://github.com/mozilla/python_mozaggregator/blob/master/mozaggregator/aggregator.py#L342). Unless there have been undocumented changes to the saved-session ping as reported by Fennec, we can be sure that these are actually present in the data.

Is it possible that there is a small group of users who have decided to enable e10s manually? Either way, this is .3% of pings, so it might be noise we can ignore.

**Comment by staktrace** [comment]
@snorp said that enabling e10s manually results in total brokenness, but maybe it works enough to send pings. I'm not sure. Considering it's a very small portion of pings it shouldn't unduly skew the data, so I'm ok with ignoring it.

**Comment by fbertsch** [comment]
Great. Best to keep an eye on it, and if it continues to seem suspicious (or gets worse) you can do some analysis in [ATMO](https://analysis.telemetry.mozilla.org/).
