### ISSUE TITLE
Add mission control to TMO landing page

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#347]
@mreid-moz or @rafrombrc, is MC in a state where we want to officially point to it? (could be in "other tools" or "main tools").
If so, what's the right URL?

**Comment by mreid-moz** [comment]
Here's a link to [Mission Control](https://data-missioncontrol.dev.mozaws.net/#/).

I think we should link to it, but I defer to @wlach for the final call.

**Comment by wlach** [comment]
I see no reason we shouldn't link to it.

The current url is:

https://data-missioncontrol.dev.mozaws.net/

This will almost certainly change in 2018, but is good for now.
