### ISSUE TITLE
Move data explorer / probe dictionary into TMO project

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#351]
We decided to move the [data explorer](https://github.com/georgf/fx-data-explorer) into the TMO project.

**Comment by chutten** [comment]
Or maybe put it into a submodule so we can keep process/issues separate?

**Comment by georgf** [comment]
We decided to:
- move data explorer into a separate mozilla project
- add it as a submodule here or so, so we get it hosted on TMO

**Comment by georgf** [comment]
I moved the probe dictionary (formerly data explorer) over here: https://github.com/mozilla/probe-dictionary

Reading [this post](https://github.com/blog/2104-working-with-submodules) on submodules, i'm not sure if these are the right approach though.

**Comment by chutten** [comment]
What would you suggest as an alternative? Maybe a similar GH->S3 ops setup to what TMO has?

**Comment by georgf** [comment]
I'm not sure what a good approach here is.
From what i understand, adding it as a submodule has some pain-points around cloning/updating for development and requires pinning specific revisions of the sub repo (adds some process, but could be useful).

So, from what i understand so far, we can:
- use submodules and pull specific sub repo revisions 
  - we probably need to add docs/tooling for dev process
  - we need to verify that this works properly with the current deployment setup
- add a deployment setup that pushes this repo and the most current version of dependent dashboards
  - this means more/new work

**Comment by georgf** [comment]
We decided to temporarily copy the probe-dictionary into this repository until we figure out submodules.
