### ISSUE TITLE
Remove prism

### ISSUE THREAD

**Issue by chutten** [mozilla/telemetry-dashboard#354]
In `lib/` we have `prism.js` and `prism.css`

Near as I can tell, neither are used.

**Comment by shikhar-scs** [comment]
@chutten If this issue still exists, may I work on this ?

**Comment by chutten** [comment]
It appears to still exist, and you may certainly work on this!

If you have any questions, please let me know.

**Comment by shikhar-scs** [comment]
@chutten You were right about that, therefore I'll remove them directly and post a PR soon.

**Comment by chutten** [comment]
Fixed by #367
