### ISSUE TITLE
Don't linkify full probe descriptions

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#358]
On the distribution & evolution dashboard, we now make the whole description a link.
This impedes readability.
Can we instead just add a "learn more" link after the descriptions?

**Comment by fbertsch** [comment]
Fine by me, that's how I originally had it.

**Comment by chutten** [comment]
If someone can design it so it doesn't look awful, sure.

**Comment by fbertsch** [comment]
Options:
- Add "more details" link after the description
- Remove text decoration on non-hover

**Comment by shikhar-scs** [comment]
We can keep it to be a toggleable display kind of thing with the title description.

Also, the text decoration can be removed. And small down array icons can be used to signify that changes can be made. 

I would like to work on this if the mentors agree to the above changes.

**Comment by georgf** [comment]
> Remove text decoration on non-hover

I don't think this is discoverable. It requires hovering over the text, which depending on the device used doesn't occur (e.g. touchscreens on mobile).

**Comment by shikhar-scs** [comment]
Well then that issue is there for each and every css hover property ever used out there on the internet. As a user I guess, majority usage of such a web application would be on a desktop/PC only. Thus, we can maybe move forward with such changes.

**Comment by georgf** [comment]
Users can surprise you. According to Analytics data, ~21% of pageviews of [telemetry.mozilla.org/new-pipeline/dist.html](https://telemetry.mozilla.org/new-pipeline/dist.html) are from mobile.

Touchscreens aside, a long text description is generally not expected to be clickable.
We need some visual cue for users to discover that there is a link. Whether that is a separate button or link or some other solution.

**Comment by shikhar-scs** [comment]
@georgf what I gathered after looking at many style displays is : 
for the desktop use we can use something like this (its related to hover only)
![downarray](https://user-images.githubusercontent.com/25258877/34680605-931de08a-f4bf-11e7-8bef-8455b0713f46.gif)

 

And for touch devices we can apply a small down arrow beside every changeable list item, something like this
![downarray gif](https://user-images.githubusercontent.com/25258877/34680614-9af289f0-f4bf-11e7-9d58-daaf86273546.gif)



Would these changes look better than the original? If not, can the mentors suggest something better.

**Comment by georgf** [comment]
These are great-looking effects.
For the specific use-case here though we want a separate link or button called "More details".
This probably looks better on a new line (possibly centered), otherwise it's odd for longer descriptions.

**Comment by shikhar-scs** [comment]
So maybe you mean to say that we can,  initially, just display one plain string consisting of the entire description without displaying options for changing them. And with the more details button we can just display the original description maybe with a bit of beautification

**Comment by georgf** [comment]
Showing the full description is possibly fine for now.
The issue that we want to fix here is that the full description is a link (to the probe dictionary).
We want to remove that and instead add a separate "More details" button or link.

**Comment by shikhar-scs** [comment]
Look at the 3rd button on the green background [here] (https://tympanus.net/Development/CreativeButtons/), we can use that if it looks good. That can just be used for the concept. The styling can further be made much better.

**Comment by georgf** [comment]
This looks like a start to me. You could try it in the page context and we can see if it works.

**Comment by shikhar-scs** [comment]
Ok I'll start with this.
