### ISSUE TITLE
alerts.tmo display has useless date range fields

### ISSUE THREAD

**Issue by staktrace** [mozilla/telemetry-dashboard#364]
Go to a URL such as http://alerts.telemetry.mozilla.org/index.html#/detectors/1/metrics/1721/alerts/?from=2017-12-22&to=2017-12-22 (which is taken from a telemetry regression alert email). Adjust the date inputs on the left side.

Expected: the graph has lines for each day in the selected range
Actual: the graph looks the same no matter what

**Comment by chutten** [comment]
The alerts.tmo frontend is [mozilla/medusa](https://github.com/mozilla/medusa), but I can take this here.

The date inputs on the left side are to filter the alerts shown on the right. If you go to bland https://alerts.telemetry.mozilla.org and select Histogram Regression Detector, it shows you the past month's alerts. You can then filter by metric and date, if there are only some you're interested in.

These days, alerts.tmo's most-used frontend is the emails it sends, which makes the UI confusing and unhelpful. We have vague plans about retiring the web frontend and addressing the use case directly on TMO in the dist view, which will address this case. But until then, we have no plans to change medusa's UI.
