### ISSUE TITLE
Extend the expiry of the "this is my current dashboard state" cookie

### ISSUE THREAD

**Issue by chutten** [mozilla/telemetry-dashboard#366]
Currently the dashboard state cookie (set in `saveStateToUrlAndCookie()`) is set to expire after only 3 days. 

We are learning from our analytics and user surveys that many users don't visit the dashboard that often.

Let's bump that expiry to a month, maybe?

**Comment by himanish-star** [comment]
@chutten , I would like  to work on this issue. May I?

**Comment by chutten** [comment]
@himanish-star Please do! Let me know if you have any questions.

**Comment by himanish-star** [comment]
~@chutten , I'm currently working on another bug elsewhere. So I'll start working on this in a while and yes I'll let you know if I have any doubts. Thanks for the help.~
  EDIT : Ok , I am starting my work on this.
