### ISSUE TITLE
Adjust Analytics

### ISSUE THREAD

**Issue by chutten** [mozilla/telemetry-dashboard#372]
The analytics as they work now work for answering the questions "What parts of TMO are used?" and "How often?"

It's not so useful for understanding what parts of `TMO/index.html` are most clicked. 

So, we need a change in our analytics. We still need pageviews from across TMO, but now we want to track usage of TMO/index separately. So external links are out. Time to track clicks on all the anchors on the index, including local ones.

Unfortunately, I already used the best name for these events (`click`) so this methodology change will have to use a less-good name. Like `nav`, I guess.

**Comment by chutten** [comment]
Actually, let's make the name TMO/index specific. So `index_nav` or `portal_nav` or something like that. Bikeshedding appreciated, @georgf @Dexterp37 if you have any ideas.

**Comment by georgf** [comment]
We can [view events per-page](https://analytics.google.com/analytics/web/#report/content-event-pages/a49796218w81627824p84513320/), so we don't need to make the name page-specific.

Re-using `click` might be fine if we just keep the change date in mind.

**Comment by chutten** [comment]
Even with proper cache control, I'm not sure we can tell if a `click` comes from an old version of the page or a new one. Since we're only expanding its reach, maybe this shouldn't matter?

**Comment by georgf** [comment]
It's probably fine over time.
