### ISSUE TITLE
wrapper: categorical histogram labels are "NaN"

### ISSUE THREAD

**Issue by leplatrem** [mozilla/telemetry-dashboard#376]
![screenshot from 2018-01-18 10-59-11](https://user-images.githubusercontent.com/546692/35092104-a866b774-fc3e-11e7-9873-b833418c5695.png)

> Note: This is a keyed categorical histogram

See https://codepen.io/anon/pen/LeXOyb

**Comment by leplatrem** [comment]
Some `else if categorical` missing here ?

https://github.com/mozilla/telemetry-dashboard/blob/aab8725f543581b90b41e89a8fa589b807fe82e3/wrapper/telemetry-wrapper.js#L512-L513

**Comment by chutten** [comment]
Almost certainly. Wrapper pre-dates categorical histograms.
