### ISSUE TITLE
`TypeError: histogramsList[0] is undefined` seen on some loads

### ISSUE THREAD

**Issue by chutten** [mozilla/telemetry-dashboard#378]
There appears to be a bug introduced by #360 where code expecting a list of histograms is reacting poorly when we give it a list of 0 length (specifically https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/new-pipeline/src/dist.js#L941)

The `else` should probably be checking that histogramsList is at least 1 in length. Further investigation is necessary.

**Comment by georgf** [comment]
I seem to trigger this 100% from [this URL](https://telemetry.mozilla.org/new-pipeline/dist.html#!max_channel_version=beta%252F58&min_channel_version=beta%252F58&measure=A11Y_TREE_UPDATE_TIMING_MS&product=Firefox).

**Comment by chutten** [comment]
Ah, that is because A11Y_TREE_UPDATE_TIMING_MS doesn't exist in beta 58.

Now at least the URL loads, but... Hm. It's still not ideal until you reload it a second time.

**Comment by chutten** [comment]
@o0Ignition0o Going to the url linked by georgf results in an unusable display. Maybe because of the .empty() ?

Maybe your code could skip the empty+rebuild entirely by turning the `else` into an `else if (histogramsList.length) {`

**Comment by o0Ignition0o** [comment]
It is pretty weird indeed, I've been able to reproduce it, and I'll land a followup pr :)
