### ISSUE TITLE
Limit the visible length of the probe descriptions

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#383]
The probe descriptions can have arbitrary length.
We should hide them after a certain length (one line on reasonable window widths?).
We can consider making them expand on user actions.

**Comment by shikhar-scs** [comment]
@georgf If you could be more clear on what `probe description` actually is, I might be able to help

**Comment by shikhar-scs** [comment]
@georgf  @chutten

**Comment by georgf** [comment]
Sorry for the delay @shikhar-scs .
If you look at [the dashboard for webrtc.nicer.stun_retransmits](https://mzl.la/2njRVJ0), the description can be rather long (see below).

We should limit the description length to 1-2 lines, with e.g. a "..." or fadeout as an overflow indicator.

We can either make it expandable to full length or just let users follow the "more details" link for now.

![long-description](https://user-images.githubusercontent.com/407696/35541816-8ed2a1fc-0511-11e8-9b45-1382239704d6.png)

**Comment by shikhar-scs** [comment]
oh, I got your point. I'll start working on this :+1:

**Comment by georgf** [comment]
This issue is free to work on by somebody else.

**Comment by Sylvia23** [comment]
Hi, I would like to start on this. Any advice on where and how to get started with the implementation is also most welcome!

**Comment by georgf** [comment]
There is some prior art and conversation in the PR #393. Does that help?

**Comment by Sylvia23** [comment]
@georgf, the feature has been already implemented using JS, but you want it using CSS. Right?
Is this the issue? If I am getting it wrong please correct me.
Thanks!

**Comment by Sylvia23** [comment]
@georgf , I have implemented it. Can you please have a look at the screenshot .
Thanks!
![screenshot from 2018-02-27 16-47-34](https://user-images.githubusercontent.com/23060217/36725890-cb1f4a4c-1bdd-11e8-8f04-83920b2a0e06.png)

CSS for this is like :
`#dist-caption, #measure-description {
  margin-left: 2em;
  white-space: nowrap;
  width : 55em;
  overflow: hidden;
  text-overflow: ellipsis;
  font-size: 1.5em;
  text-align: center;
  border: 1px solid #000000;
  background: yellow;
  padding: 0.1em;
}`

For this, files 

- dashboards.css

- dist.html

- evo.html

- evo.js

- dist.js

have been affected.

**Comment by georgf** [comment]
This looks like the right visual approach to me!
Some quick notes:
- The border and background color are just to highlight this for the screenshot?
- I'm not seeing the "More details" link in the screen shot.

**Comment by Sylvia23** [comment]
- Yes, the color and border is just to highlight the feature. I will remove it now.

- "More details" link is there. The screenshot contained just the CSS part for an example of a long caption. Please have a look at the screenshot attached.


![screenshot from 2018-02-27 20-44-40](https://user-images.githubusercontent.com/23060217/36736594-0ada9800-1bff-11e8-96a9-ab8cd5925a21.png)

**Comment by Sylvia23** [comment]
@georgf , Finally, UI looks like this for long captions :

![screenshot from 2018-02-27 21-40-26](https://user-images.githubusercontent.com/23060217/36739770-c2d7d632-1c06-11e8-96cf-cf7cc711f7ef.png)

**Comment by Sylvia23** [comment]
@georgf , Can you please review #418 whenever you are free. Thanks!

**Comment by georgf** [comment]
Hi, i got back from my weekend and looked over it!
