### ISSUE TITLE
Update telemetry-wrapper's documentation to recommend using the minified MG

### ISSUE THREAD

**Issue by chutten** [mozilla/telemetry-dashboard#390]
telemetry-wrapper's docs recommend the use of `metricsgraphics.js` when we also have a much smaller and faster-to-parse `metricsgraphics.min.js`

We should update the docs to recommend it instead.

**Comment by himanish-star** [comment]
@chutten, I have the changes ready. Can I file a PR ?

**Comment by chutten** [comment]
By all means, go ahead.

**Comment by himanish-star** [comment]
Thanks, I have filed a PR
