### ISSUE TITLE
Replace protocol-less URLs with HTTPS URLs

### ISSUE THREAD

**Issue by robhudson** [mozilla/telemetry-dashboard#401]
Currently when loading an HTML file from the repo locally using `file://`, the URLs referenced that use a protocol-less format do not work as the resources come from the internet.

I propose that we replace these with full URLs with the `https://` protocol so these work both locally (via `file://` loading) and on TMO (which uses HTTPS).

**Comment by chutten** [comment]
Oh, the CDN-sourced ones that are written as `//`? Seems valid.
