### ISSUE TITLE
Add space between "Amplitude" and lock icon on landing page

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#405]
On `/index.html`, we're missing a space before the lock icon for the link to Amplitude.

**Comment by Sylvia23** [comment]
I will start working on this. Looking forward to my contribution. Thank you so much!

**Comment by Sylvia23** [comment]
@georgf , I think space should be added before the lock icon for "Mozilla Data Collective" as I can see on the webpage.

**Comment by georgf** [comment]
Yes, good catch!

**Comment by Sylvia23** [comment]
@georgf , The bug has been fixed. I got to know when I was just about to submit the PR. But I don't know how. See here, [https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/index.html#123](url)

**Comment by georgf** [comment]
It turns out this was fixed with amazing timing by #403 as seen [here](https://github.com/mozilla/telemetry-dashboard/commit/0aede5a3ba2127a4e4982d9c10a7928f706ae563#diff-eacf331f0ffc35d4b482f1d15a887d3b).
I'll close this issue :)
