### ISSUE TITLE
Move landing page column with twitter feed to the right

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#407]
On the [landing page](https://telemetry.mozilla.org/), the middle column contains a twitter feed.
User feedback tells us that a) this is not useful to most and b) that they tend to miss the other tools in the right-most column.

In `/index.html`, we should move the twitter column to the right, after the column that contains "getting help" and "other tools".

**Comment by Sylvia23** [comment]
Hi @georgf , Can you please review the PR. Thanks!

**Comment by georgf** [comment]
Fixed by #410.
