### ISSUE TITLE
Hide release channel data from publish dashboard

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#408]
We are working on not showing data from Firefox release in the backend, but this might take a little.
In the mean-time, we can stop showing "release" in the front-end, like the [dropdown here](https://screenshots.firefox.com/zEtLo4J097y0kJ6n/telemetry.mozilla.org).

This potentially affects evo.html, evo.js, dist.html, dist.js & dashboards.js in `/new-pipeline`.

chutten would probably know more about where a good place for this change is.

**Comment by ecomerford** [comment]
Hey @georgf! I would love to work on this issue if no one else has started working on it yet!

I'll happily accept advice on where to begin. @chutten seems like you're the one to ask?

Thank you both!

**Comment by georgf** [comment]
Welcome, please go ahead!
I'll leave it to chutten to fill in some details.

**Comment by chutten** [comment]
Uh oh, it appears as though this was double-posted. I think the original is #399

**Comment by chutten** [comment]
@georgf ^^

**Comment by ecomerford** [comment]
Oops! Okay, I'll keep looking around for something to work on. Thanks!

**Comment by georgf** [comment]
Sorry, that was my bad!
