### ISSUE TITLE
Remove e10s setting from telemetry dashboards

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#411]
e10s (using multiple processes) is the standard in Firefox now, so it's not useful anymore to break this out anymore in the dashboard.
We should remove this from the front-end:
![e10s](https://user-images.githubusercontent.com/407696/36686376-84047608-1b26-11e8-8507-cf6ba679fc7c.png)

This potentially affects evo.html, evo.js, dist.html, dist.js & dashboards.js in `/new-pipeline`.

**Comment by Sylvia23** [comment]
Hi @chutten , Can you please review the new PR on this issue. Thanks!

**Comment by chutten** [comment]
I don't see a new PR. It might be best to (force-)push to the old PR, so we keep the context together.

**Comment by Sylvia23** [comment]
Ohh. Okay @chutten 
I will push again.

**Comment by Sylvia23** [comment]
Hi @chutten ,  #413 
 Can you view this PR ?
