### ISSUE TITLE
Remove release warning message from dashboards

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#412]
After #399 is fixed, we can remove the top-level warning message about release data:
![message](https://user-images.githubusercontent.com/407696/36686528-00369e68-1b27-11e8-8af6-7e9065640887.png)

**Comment by georgf** [comment]
This probably affects evo.html and dist.html in `/new-pipeline`.

**Comment by chutten** [comment]
This task is to just undo the work I did in #341 (reworded in #343), commenting out the two notices so they no longer display.

**Comment by Sylvia23** [comment]
#417 Please review this. Thanks !

**Comment by georgf** [comment]
We'll need to fix #399 first before we can merge this, otherwise we'll have incomplete release data in the dashboard without any explanation.
