### ISSUE TITLE
Show only one link to measurement dashboard on landing page

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#414]
Currently we show two links to basically the same dashboard on the landing page: "measurement dashboard" and "evolution dashboard".
After #409 is fixed, we can:
- remove the "evolution dashboard" link 
- change the text to something like "View measure distributions and evolutions over time."

**Comment by chutten** [comment]
The phrasing will need some iteration. "View" and "measure" can both be verbs, so it reads a little awkwardly.

**Comment by georgf** [comment]
Erin will work on this, we can merge it after #409 was fixed.

**Comment by ecomerford** [comment]
@georgf Working on this now! I'm trying to push up my branch but am getting a 403 error: 

"remote: Permission to mozilla/telemetry-dashboard.git denied to ecomerford.
fatal: unable to access 'https://github.com/mozilla/telemetry-dashboard.git/': The requested URL returned error: 403"

Do I need my permissions updated to push? Thanks!

**Comment by georgf** [comment]
Push access to the repository is limited to specific people.
The GitHub workflow usually is to:
- Fork the repository into your account and work on that.
- Once you're happy with the changes, push them to your fork.
- Then open a pull request, asking for review and for the changes to be pulled into this (main) repository.
[This guide](https://help.github.com/articles/fork-a-repo/#propose-changes-to-someone-elses-project) is probably more helpful than my description though.

Let me know if you run into issues with this!

**Comment by ecomerford** [comment]
Got it, thank you!

**Comment by georgf** [comment]
Fixed by #421, thanks!
