### ISSUE TITLE
Short link button is broken

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#422]
I noticed that the short url button (top right corner) is broken in both the distribution and the evolution view. This is on the current gh-pages branch, it may not have made it through CDN yet for everyone.

Clicking it results in an error logged:
> TypeError: shortUrl is undefined[Learn More]

**Comment by chutten** [comment]
Works for me. http://mozilla.github.io/telemetry-dashboard/new-pipeline/dist.html#!cumulative=0&end_date=2018-02-27&keys=__none__!__none__!__none__&max_channel_version=nightly%252F60&measure=GC_MS&min_channel_version=null&processType=*&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2018-01-22&table=0&trim=1&use_submission_date=0 shortens to https://bit.ly/2GQHCDx

**Comment by georgf** [comment]
This is an issue limited to local testing.
When running this on localhost, the short url request is not successful and we don't handle this gracefully.

Closing, given that this only an issue locally.
