### ISSUE TITLE
Add icons for each section on landing page

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#426]
To aid visually guided people, we should add an icon to each main section on [the landing page](https://mozilla.github.io/telemetry-dashboard/):

<img width="400" alt="screen shot 2018-03-01 at 18 14 53" src="https://user-images.githubusercontent.com/407696/36858895-0d6cecd8-1d7d-11e8-9a91-b7c07e7ed2e1.png">

**Comment by georgf** [comment]
Shreya will probably work on this.

**Comment by georgf** [comment]
This will involve changing `/index.html`.
I propose we use font-awesome icons for this:
- ["chart-bar"](https://fontawesome.com/icons/chart-bar?style=solid) for main tools
- ["book"](https://fontawesome.com/icons/book?style=solid) for documentation
- ["question-circle"](https://fontawesome.com/icons/question-circle?style=solid) for "getting help"
- ["wrench"](https://fontawesome.com/icons/wrench?style=solid) for "other tools"

font-awesome icons are added by adding a `<i class="$iconName"></i>`, e.g. `<i class="fas fa-wrench"></i>`.

**Comment by shreya99oak** [comment]
Yes, sure!

**Comment by manishakeim** [comment]
Is this issue assigned to anyone ? or Can I claim it ?

**Comment by georgf** [comment]
This was already fixed in #433, we just forgot to close this issue.
If you can't find any other open issues though, let us know, we'll find something!

**Comment by manishakeim** [comment]
@georgf Can you please help me find one, as I am a beginner I was finding more of 'good first issue' and there are no such issues with these labels left how should I proceed with contributing to this project for Outreachy?

**Comment by georgf** [comment]
Hi @manishakeim, sure! How about #469?
I should call out that there are active applications already on this Outreachy project, while others are still looking for applications. Maybe take a look on other projects as well :)
