### ISSUE TITLE
Replace unused .scrollable-dashboard-list style with just .dashboard-list

### ISSUE THREAD

**Issue by chutten** [mozilla/telemetry-dashboard#431]
In #344 we made some changes to `style/dashboard.css` for the main portal page at telemetry.mozilla.org

In #403 we then started using `new-pipeline/style/dashboard.css` instead. This lost us a few styles, specifically the ones we redirected from `.scrollable-dashboard-list` to be just `.dashboard-list`

We need to replay #344's `dashboard.css` changes on `new-pipeline/style/dashboard.css` to bring the styles back the way they used to be.

**Comment by JQuinnie** [comment]
Hi @chutten ,
I'd like to work on this issue if possible, thanks!

**Comment by chutten** [comment]
@JQuinnie Please do! Let me know if you have any questions.

**Comment by JQuinnie** [comment]
Hi @chutten ,

I am comparing the two mentioned files, `style/dashboard.css` and `new-pipeline/style/dashboards.css` and do not see any noticeable visual changes to the main portal page.

on #344 the changes are [here](https://github.com/mozilla/telemetry-dashboard/blob/d0fb38625f1649763ee1b60f73505176353f1dce/style/dashboards.css#L20-L27) and actually mostly reflected on #403 with the removal (rename) of `style/dashboards.css` to `new-pipeline/style/dashboards.css`.

Perhaps I am missing something or not looking at the right place... can you give me an example of a noticeable change?

**Comment by chutten** [comment]
It's not a large difference, I only noticed because I've used this site for years : )

The borders aren't supposed to surround the list items, they're just supposed to separate them. I've taken a couple of screenshots to illustrate. Here's the way it is now: https://screenshotscdn.firefoxusercontent.com/images/38dbb6a1-0669-469b-8636-5e13a9be6844.png

And here's the way I expect it to be: https://screenshotscdn.firefoxusercontent.com/images/ea787544-0386-4ef4-a22d-9cf076ef9d1b.png

**Comment by JQuinnie** [comment]
Sounds good! I have PR #434 ready for review.
