### ISSUE TITLE
Add icons for some actions in the telemetry dashboard

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#437]
Some actions in dist.html & evo.html could use icons to be easier to notice.
The buttons at the top-right and the "advanced settings" come to my mind.

We include font-awesome 4, so we can use [icons from there](https://fontawesome.com/v4.7.0/icons/).

**Comment by georgf** [comment]
Carolina will look into this.

**Comment by paucaro** [comment]
Yes, sure!
