### ISSUE TITLE
The stats button for the probe dictionary is not working

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#441]
For the [probe dictionary](https://telemetry.mozilla.org/probe-dictionary/), the "stats" button broke recently.
It does render the stats i expect, but just keeps showing the search results.

This is not a good starting issue, it will require a bit of investigation.

**Comment by shreya99oak** [comment]
Hi, can I work on this?

**Comment by georgf** [comment]
Hi Shreya, i think this will require a little prior JavaScript debugging experience.
Does that fit? :)

**Comment by shreya99oak** [comment]
Oh! then can I work on the bug which requires us to add a shortlink button to the probe dictionary?

**Comment by georgf** [comment]
It looks like Sylvia started to work on this.
How about #445?

**Comment by georgf** [comment]
#459 has better details, so i'm closing this one.
