### ISSUE TITLE
Add shortlink button to probe dictionary

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#443]
To make it easier to pass around links to specific searches in the [probe dictionary](https://telemetry.mozilla.org/probe-dictionary/), we should add a button to get shortlinks.

We can use the [Telemetry dashboard](https://telemetry.mozilla.org/new-pipeline/dist.html) as an example, which has a "permalink" button in the top right. The code that handles it [is here](https://github.com/mozilla/telemetry-dashboard/blob/17eacb63d4a7456f549028d6f45557ded7f88e5a/new-pipeline/src/dashboards.js#L130).

This should be added to the top bar buttons.

**Comment by Sylvia23** [comment]
@georgf, I would like to start working on this. Can I proceed ?
Thanks!

**Comment by georgf** [comment]
Sure, i assigned it to you!

**Comment by shreya99oak** [comment]
Thanks:)

**Comment by shreya99oak** [comment]
Sorry wrong post

**Comment by Sylvia23** [comment]
@georgf , Can you please review the PR #450. Thanks!
The UI now looks like this with the "Get Permalink" button.
![screenshot from 2018-03-08 01-51-35](https://user-images.githubusercontent.com/23060217/37116092-28295692-2273-11e8-8662-38bd8e0ef348.png)
