### ISSUE TITLE
Error showing detail view for use-counters in probe-dictionary

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#444]
Opening [this view](https://telemetry.mozilla.org/probe-dictionary/?detailView=histogram%2FUSE_COUNTER2_DATATRANSFER_ADDELEMENT_PAGE) in the probe-dictionary, the view doesn't finish loading.
Looking into the Firefox web console, i see an error:
> ReferenceError: last is not defined[Learn More]

Using the debugger, we can identify where this error happens and fix it.

**Comment by mindip** [comment]
If no one's working on this, I was planning on checking it out.

**Comment by georgf** [comment]
Sure Mindi, let us know if you have any questions!

**Comment by mindip** [comment]
Hey so I made a pull request (above). It seems like we just needed to initialize an array. Let me know if 
 there's more to the problem or if there's a better way to push changes.

Edit: [View (fixed)](https://mindip.github.io/telemetry-dashboard/probe-dictionary/?detailView=histogram%2FUSE_COUNTER2_DATATRANSFER_ADDELEMENT_PAGE)
