### ISSUE TITLE
Improve the probe dictionary C++ guard display

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#445]
In the detail view for e.g. the data point [A11Y_CONSUMERS](https://telemetry.mozilla.org/probe-dictionary/?detailView=histogram%2FA11Y_CONSUMERS), we show an empty "C++ guard" field.

We should improve how this is shown by:
- moving the field down (this can be last) (in `probe-dictionary/index.html`)
- showing an italic "*none*" for the value when the field is empty (in `probe-dictionary/explore.js`)

**Comment by georgf** [comment]
Shreya will probably work on this.

**Comment by shreya99oak** [comment]
Okay:)

**Comment by chutten** [comment]
A fun feature that not everyone knows about is the `:empty` CSS pseudo-class. Pair that with `:after` and we might be able to add in the italic "_none_" without any script.

**Comment by shreya99oak** [comment]
so do we want "none" to be displayed only when the c++ guard field is empty or even when any other field is empty?

**Comment by chutten** [comment]
I say go for whichever solution has an implementation that seems easiest to understand.

**Comment by shreya99oak** [comment]
made a pull request..the changes look like this..
![c](https://user-images.githubusercontent.com/32118977/37115433-1f8dd8d4-2271-11e8-98ae-5a16748421de.png)

**Comment by georgf** [comment]
This was fixed by #449.
