### ISSUE TITLE
Make probe dictionary header links more discoverable

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#446]
> It's hard to find the "Find probes" and "Stats" links at the top of the page. We should make them more discoverable (e.g. underline them).

(this comes from mozilla/probe-dictionary#15)

**Comment by JQuinnie** [comment]
hi @georgf, I have the PR open under the [Probe Dictionary Issue #15](https://github.com/mozilla/probe-dictionary/issues/15).

Is there a way to link it here as well, to close out this issue?

**Comment by JQuinnie** [comment]
@georgf Got that PR #453 ready to go with your request of it from the Telemetry site, take a review when free.

[Live site for reference](https://jquinnie.github.io/telemetry-dashboard/probe-dictionary)
