### ISSUE TITLE
Use checkboxes in dashboards "advanced settings"

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#447]
The "advanced settings" in the distribution and evolution dashboard should just be checkboxes instead of radio buttons.

This will require a bit of rewording and reordering of elements so that it makes sense.

**Comment by georgf** [comment]
@PaulaAsto, do you want to work on this?

**Comment by paucaro** [comment]
Yes, sure :)

**Comment by georgf** [comment]
Here is a simple mockup of how this could look for one option:
<img width="574" alt="screen shot 2018-03-08 at 14 36 02" src="https://user-images.githubusercontent.com/407696/37153918-8eab32da-22de-11e8-8e77-222f20238c8a.png">
