### ISSUE TITLE
Make the probe-dictionary search results header sticky

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#448]
In the [probe-dictionary search results](https://telemetry.mozilla.org/probe-dictionary/), it would be great if the table header is always in view, no matter where you scroll to.

Chris mentioned that [`position: sticky`](https://developer.mozilla.org/en-US/docs/Web/CSS/position) might help here.

**Comment by georgf** [comment]
Rose Wan is probably working on this.

**Comment by rosexw** [comment]
Thank you, Georg. This is a good first assignment. I'll work on this, after I get my dev environment and web server set up!

**Comment by rosexw** [comment]
I submitted a pull request for this.

I also added a different pull request to Command Line to use NPM to run the web server.

**Comment by gargshruti30** [comment]
@chutten Can i work on this issue ?

**Comment by gargshruti30** [comment]
@chutten @georgf  I was able to solve this issue.
Can I make a PR ?

**Comment by gargshruti30** [comment]
@georgf @chutten @badboy I was able to solve this issue.
Here is a screenshot attached.

Please advice if I can make a PR.

![screenshot from 2018-03-17 19-27-38](https://user-images.githubusercontent.com/34654829/37568029-94213d9e-2af5-11e8-8601-2141b996e4a6.png)

**Comment by chutten** [comment]
Yes @gargshruti30 you can submit a PR to solve this issue.

**Comment by gargshruti30** [comment]
@chutten okay. I will do that.

**Comment by gargshruti30** [comment]
@chutten I had already made a PR (#472 ). The changes have been added to that. Kindly review the PR.

**Comment by chutten** [comment]
One PR per issue, please : ) If you keep each issue's work on a separate branch, that can help out in both thinking about your solutions and getting them merged upstream.

**Comment by gargshruti30** [comment]
@chutten So should I make 2 different branches and then make 2 PR's for both the issues separately ?
Please suggest.

**Comment by chutten** [comment]
Yes please.
