### ISSUE TITLE
The dashboard should link to probe-dictionary, not fx-data-explorer

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#455]
The "more details" link on the dashboard links to `https://georgf.github.io/fx-data-explorer/...`.
We now moved that project into this repository in #351, so the link should now go to `/probe-dictionary/...`.

**Comment by georgf** [comment]
This will require changing `dashboards.js`. See the [contribution guide](https://github.com/mozilla/telemetry-dashboard/#contributing-to-the-telemetry-dashboard) for how to get started.

**Comment by Sylvia23** [comment]
@georgf, I noticed the same thing yesterday and was about to report. I have looked into it and tried to change. 
I replaced the `baseUrl` `https://georgf.github.io/fx-data-explorer/index.html`  with `https://telemetry.mozilla.org/probe-dictionary/` and checked it in my local machine. It's working fine.
But if the domain name of `probe-dictionary` gets changed as there has also been a discussion on this then we will have to change it again in dashboard as well. 
Hence, Is there an alternate approach (e.g. linking the URL to the GitHub repository of probe-dictionary)? Please suggest. Thanks!
