### ISSUE TITLE
Add a clear top bar to Telemetry Portal

### ISSUE THREAD

**Issue by shreya99oak** [mozilla/telemetry-dashboard#456]
@georgf  I'll start working on this!
To add-
 A suitable colored top bar which will include the title "Telemetry portal" and "report bug" on the right.

**Comment by kdrosado** [comment]
@georgf , @robhudson , Has #468 been assigned? If not, can I work on it?

**Comment by georgf** [comment]
Hi, yes, it has been assigned :)
You can tell by either the "assigned" label on the right or if a person is listed under "assignees".

There are more [available issues](https://github.com/mozilla/telemetry-dashboard/labels/mentored). If you can't find any, just let us know!

**Comment by gargshruti30** [comment]
@georgf Can I work on this issue ?

**Comment by wlach** [comment]
I think this was fixed at some point.
