### ISSUE TITLE
Only show URL params that have non-default values

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#458]
We store a lot of values in the URL params. We could greatly shorten the links if we only use params for non-default values.

**Comment by georgf** [comment]
Shruti9520 wanted to work on this.

**Comment by kdrosado** [comment]
@georgf , @chutten , Has this been assigned?  If not, can I work on it?

**Comment by chutten** [comment]
This is currently assigned to @shruti9520. It may have fallen by the wayside, though, so let's check.

@shruti9520, are you still working on this? Do you need help? Would you prefer if @kdrosado started working on it?

**Comment by Sylvia23** [comment]
@chutten, Is it still to be worked upon? Can I take this up if nobody is working on it?

**Comment by Shruti9520** [comment]
@Sylvia23 Yes, please. You can work on this.

**Comment by Sylvia23** [comment]
@chutten , I have gone through the code for `probe-dictionary`. Probably, [here](https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/probe-dictionary/explore.js#L523) is the part of code that take care of the `params`.
Can you please give some pointers what is exactly intended in the issue. Thanks!

**Comment by chutten** [comment]
If you go to the probe dictionary via this url: https://telemetry.mozilla.org/probe-dictionary/

You actually, eventually, end up at this url: https://telemetry.mozilla.org/probe-dictionary/?search=&searchtype=in_any&optout=false&channel=any&constraint=is_in&version=any&view=search-results-view

All of those query parameters are at their default values. We don't need them to be in the url if they are default -- the code knows what the default values are.

This task is to not put any parameter in the url if it is set to its default value.
