### ISSUE TITLE
Back/Forward breaks if you close details with the 'x'

### ISSUE THREAD

**Issue by JQuinnie** [mozilla/telemetry-dashboard#463]
STR:

Open a detail view
Click 'x' to close
hit the browser back button.
Basically 'x' needs to pop the history state.

Reference Probe-Dictionary [issue 25](https://github.com/mozilla/probe-dictionary/issues/25)

**Comment by chutten** [comment]
@JQuinnie how are things on this Issue? Anything I can help with?

**Comment by JQuinnie** [comment]
Hi @chutten ,

I have a project due so was pretty busy, apologies as I did plan on working on this issue sooner.

I have looked into the flow of the detail view and have noticed;
- User clicks `+` to open detail-view
- User clicks `x` to close detail-view (#close-detail-view)
- function `hideDetailView()` fires
- class of `hidden` is removed from "search-view"
- function `updateSearchParams()` fires
- that function resets search values to "" and turns `pushState = false`
- when `pushState = true`, `window.history.replaceState` fires

What I'm thinking is that I need to save the state of the browser history upon clicking '`x`' to close detail-view... that way when the user presses browser back button, the browser can populate the previous state. Do I need to include a `history.pushState` then `window.onpopstate` in the click event upon closing detail-view? Appreciate your guidance.

**Comment by chutten** [comment]
You're definitely in the right part of the code, but I think what we need is a `window.history.popState` when the user clicks the '`x`' to match the `window.history.pushState` that we did when the user clicked the '`+`'

Does a `window.history.popState` in `hideDetailView` get the job done? Does going into a detail view still increase the history length, and does clicking `x` decrement it now? (you can check the length in the console by querying `window.history`)

**Comment by JQuinnie** [comment]
I am updating function `updateSearchParams(true)` to take a value of `true`, this will call the `window.history.pushState` to register search-view as a state, and when user clicks `x` on detail-view, the search-view will populate.

[Published Site](https://jquinnie.github.io/telemetry-dashboard/probe-dictionary)

Can you check my live site to see if it has the intended effect, prior to PR?

Thanks!

**Comment by chutten** [comment]
That has the unintended effect of putting the detail view open and close into the history. Which might technically fix this bug, now that I'm reading it a different way.

Unfortunately I didn't specify clearly what I wanted at the beginning :S

What I want is for the details view '`x`' to be treated the same as a press of the Back button. I want it to go back one state in the browsing history, not push another one on top. Thus

1. From the probe dictionary main page (history of length 1)
2. Go into the details view for a probe (history of length 2)
3. hit 'x' or hit Back
4. Be back at the probe dictionary (history of length 1)

Does that make it more clear?

**Comment by JQuinnie** [comment]
@chutten ok, that makes sense.

I thought of implementing the `hideDetailView()` much like the back button when `x` is clicked.
I tried something like this;

> function hideDetailView() {
>   document.getElementById("probe-detail-view").classList.add("hidden");
>   document.getElementById("main-tab-holder").classList.remove("hidden");
>   document.getElementById("search-view").classList.remove("hidden");
>   gDetailViewId = null;
>   window.history.back();
> }

This allows the `x` to act like a browser back button... but I don't think it captures the history length quite like you wanted it, history length didn't change into or out of details-view... but the back/forward buttons work as you expect.

[Published Site](https://jquinnie.github.io/telemetry-dashboard/probe-dictionary/)

**Comment by chutten** [comment]
It seems a little slower than before, but the user behaviour's what we want.

The problem becomes when someone links directly to a detail view (like we do from the Measurement dashboards), and then clicks '`x`'. They'll be sent back to the previous page instead of closing the detail view and showing the search.

Now, this might or might not be fixed by replacing back with `window.history.popState`, but I still think we should use `popState` to mirror the `pushState` we call when we push the detail view into view.

**Comment by JQuinnie** [comment]
Hi @chutten ,
I've been researching the window states and have come to a conclusion that there is no property called `popState` on the window object, only a popstate event. It is not a simple `window.history.popState` to counter the `pushState` as one would think there would be...

What we can do is probably make a conditional in the `hideDetailView` function that would return the '`x`' as a back button if the user came from the search-view and all others origins would use the previous `updateSearchParams` function, see below;

```
if (window.history.lastURL = searchViewURL) {
  window.history.back();
  } else {
    updateSearchParams();
  }
}
```
The only thing is that I will need to find the incoming .lastURL to compare to the `searchViewURL`.

Trying to make '`x`' function like a back button for some cases, but not all without having a reciprocal `popState`... Thoughts?

**Comment by chutten** [comment]
You are of course entirely correct, and I blame myself for uncareful reading of the history API documentation.

One thing we could do to get the last url is to store it in the state as we push it. Of course, we don't actually need the url itself, we just need an indication that calling `window.history.back()` will do what we want it to do. So we could save a boolean or a sentinel value of any kind.

What do you think of that approach?

**Comment by chutten** [comment]
Unassigning and deprioritizing due to inactivity.

**Comment by abhinandan1995** [comment]
Hey I'd like to start on this. @chutten And just for the approach, can I use an extra parameter in the url?

**Comment by chutten** [comment]
Apologies for the delayed response, I was out of the country. 

Using the url to store state is a valid tactic, but for this use case I think using the History API would be better. Putting state in the URL would mean sharing it between people when sharing links and having identical views have multiple different URLs that would resolve to them.

Does that make sense?

**Comment by wlach** [comment]
Sorry for the late response on this, I think this got lost in the shuffle.

This seems to have been fixed with the react-based probe dictionary (https://github.com/mozilla/probe-dictionary). As such, I'm going to close this issue.
