### ISSUE TITLE
Rename "Dashboards Home" to "Telemetry portal"

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#469]
In `new-pipeline/dist.html` and `evo.html`, we should rename the "Dashboards Home" button to "Telemetry portal".

**Comment by georgf** [comment]
manishakeim is probably looking into this.

**Comment by gargshruti30** [comment]
@georgf Hey I am Shruti. I am first time aspirant of Outreachy and I want to contribute in this project.
Can you tell me some beginner level issues  and why is this issue still open, is there anything left which has to be done ?

**Comment by gargshruti30** [comment]
@georgf I got the problem can I work on this issue ?
I am eager to contribute.

**Comment by gargshruti30** [comment]
@georgf 
I corrected it. Just have a look at it.
![screenshot from 2018-03-15 09-45-53](https://user-images.githubusercontent.com/34654829/37444041-bc83ecd6-2835-11e8-9edf-bff1f3283f70.png)
![screenshot from 2018-03-15 09-46-04](https://user-images.githubusercontent.com/34654829/37444042-bcc0ebc2-2835-11e8-8309-091a4d2c4d0a.png)
