### ISSUE TITLE
Error loading probe dictionary

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#473]
When opening [this link](https://telemetry.mozilla.org/probe-dictionary/?searchtype=in_name&optout=false&channel=nightly&constraint=is_in&version=any&detailView=histogram%2FUSE_COUNTER2_DEPRECATED_IDBOpenDBOptions_StorageType_PAGE&search=use_counter2_deprecated_idbopendboptions_storagetype_page), it does not load successfully.

The console shows:
> ReferenceError: last is not defined

**Comment by georgf** [comment]
This will require a little debugging experience... or willingness to learn it :)

**Comment by Insiyaa** [comment]
Hey! I'd like to look into this...

**Comment by gargshruti30** [comment]
Hey. 
I would like to work on this issue..

**Comment by georgf** [comment]
It looks like this was just fixed by #470, yay.
