### ISSUE TITLE
Link to use counter dashboard when displaying USE_COUNTER2_* probes

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#474]
*(Based on local user feedback)*

In the measurement dashboard, when showing a probe like [USE_COUNTER2_JS_ASMJS_PAGE](https://mzl.la/2tUm4Ei), we should show a link to the use-counter dashboard.

For all probes whose name starts with `USE_COUNTER2_`, we should link to the right section of the [use counters dashboard](http://georgf.github.io/usecounters/).
For the example here, this would [go here](http://georgf.github.io/usecounters/#kind=page&group=JS&channel=beta&version=59).

We should show the link right under the probe description, e.g. labeled "View in use counter dashboard".

**Comment by georgf** [comment]
This would affect `dist.html`, `evo.html` and probably `dashboards.js` in `new-pipeline/`.

**Comment by ecomerford** [comment]
@georgf Do you mind if I give this a shot?

**Comment by chutten** [comment]
By all means, please do! (georgf is on vacation for the next little while, so I'll be pretending to be him in the interim)

**Comment by ecomerford** [comment]
@chutten I'm having trouble selecting the text of the "Value being measured" button. 

Upon inspecting the element, it appears that the text is within a button called `.multiselect-selected-text`.  The text it prints out _does_ include the name of the selection (see below).
 
![screenshot-1](https://user-images.githubusercontent.com/35710168/37631505-3f37621a-2ba7-11e8-9483-d03024ca72f0.png)

_But_ when I try to use this to create a variable,
![image](https://user-images.githubusercontent.com/35710168/37631532-5c6d54e8-2ba7-11e8-9b55-99b6f98c16a4.png)

The variable itself doesn't contain the same text, thus my code doesn't work. In the first screenshot above, you can see what was logged from `measureSelection` in the console.

I hope this makes some sense.

**Comment by chutten** [comment]
You might be able to get it with `$("#measure").val()`

Does that help?

**Comment by ecomerford** [comment]
@chutten `$("#measure).val()` logs `null`. That's why I tried to use the classes I found when inspecting the element, but that doesn't appear to be working, either. I may try to start over because my initial approach hasn't panned out.

If you or @georgf have any suggestions for where to start for this one, that'd be a big help!

Thank you! :)

**Comment by chutten** [comment]
Odd, the only time I see `$("#measure").val()` being `null` is during load. And during load we don't need descriptions : )

Maybe it's a matter of timing, then?

**Comment by ecomerford** [comment]
Since I put my code within the larger document ready function, shouldn't it be executing once the page loads? I still get `null` when I do that, though.

**Comment by georgf** [comment]
I wonder, can you instead of your current approach just add to the `getDescription()` function or a related one?
They already get passed a `metric` parameter, which would solve your problem.

**Comment by ecomerford** [comment]
Thank you for the suggestion! This is working to select the value of the measurement. 

Do you think the best approach is to use a series of `if...else` statements to determine if each different group is selected and if so, append the correct link into an empty div? Ie:

`if (metric.indexOf("DATATRANSFER") > 0) {
  ...}`

Then append the link to the use counter for data transfer group, and so forth.

That's what I was planning to do but it seems like it could get a bit lengthy?

**Comment by georgf** [comment]
All the [use counter names](https://telemetry.mozilla.org/probe-dictionary/?search=use_counter2) follow the same pattern:
`USE_COUNTER2_<group>_<name>_<PAGE/DOCUMENT>`.
We're not really tracking the different values for `group` and `name` as Firefox engineers may add more at any time.

What we do for the use counter dashboard is [to just split out](https://github.com/georgf/usecounters/blob/master/index.html#L425) the `<group>` part.
We can probably follow a similar approach here.

**Comment by georgf** [comment]
Closed by #520.
