### ISSUE TITLE
Telemetry Alerts

### ISSUE THREAD

**Issue by gargshruti30** [mozilla/telemetry-dashboard#476]
When we click Telemetry Alerts in https://telemetry.mozilla.org/, we get http://alerts.telemetry.mozilla.org/index.html

After this when we click Telemetry Main-thread IO or Unpacked Add-on File Scan, we always get an error message 'Failed to load alerts'.
Is this a bug or what ?

**Comment by chutten** [comment]
Those two regression detectors aren't supported any longer and can be removed. That's a different project, though, called medusa: https://github.com/mozilla/medusa

If you'd like you can file issues there and fix them. It's written in clojure, though, so if you aren't familiar with Lisp-like languages it might not be friendly to introductory contribution.

**Comment by gargshruti30** [comment]
okayy.. Thanks :)
