### ISSUE TITLE
 'Reports portal' lacks responsiveness 

### ISSUE THREAD

**Issue by shradha-khapra** [mozilla/telemetry-dashboard#477]
The navigation bar in 'Reports portal' under other tools section lacks responsiveness. Also the 'Write a post' button moves out of the navigation bar when screen size is reduced.

**Comment by Sylvia23** [comment]
I think it's not a part of `Telemetry-Dashboard`. The `Reports portal` is embedded in the `Telemetry-Dashboard`. Hence, the problem belongs to `Reports portal` repository. 
Please correct me if I am wrong @chutten @georgf .

**Comment by chutten** [comment]
@Sylvia23 is correct. The Reports Portal is reports.tmo which is a different project altogether. The current plan is to replace it sometime this year, so we can leave a non-breaking bug like this alone for now and work on the new one when it's released.

Thank you for filing the bug though!
