### ISSUE TITLE
error in 'Generate Dashboard' button

### ISSUE THREAD

**Issue by shradha-khapra** [mozilla/telemetry-dashboard#479]
In the Dashboard Generator section the 'Generate Dashboard' button remains disabled when no dashboard is added but when we add some dashboards and delete all of them from the list the button becomes enabled and generates a codepen.

**Comment by chutten** [comment]
This looks like a good one someone could get started on if they wanted.

**Comment by shradha-khapra** [comment]
Could you please assign it to me as I want to work on it.

**Comment by chutten** [comment]
This is the best I can do for now. Github does assignees in strange ways that we're not 100% sure we understand just yet :S

**Comment by shradha-khapra** [comment]
thank you :)

**Comment by preeti98** [comment]
Hi! This is Preeti Mukherjee. I have just recently started learning JavaScript. So, I would like to work on this bug in case no one else is working on this. Thanks in advance!

**Comment by jarkyll** [comment]
@preeti98 Has there been an update on this story?

**Comment by nvamsikrishna05** [comment]
I can see that this issue has been fixed. Now the generate dashboard button becomes disabled after adding and removing all dashboards. So, this issue can be closed.
