### ISSUE TITLE
'FIREFOX' is hiding on decreasing width of update-orphaning page

### ISSUE THREAD

**Issue by gargshruti30** [mozilla/telemetry-dashboard#484]
On decreasing the width of update-orphaning page, the 'Firefox' in the heading is hiding behind the 'Report week' button.

@chutten Can I work on this issue to correct it ?

![screenshot from 2018-03-20 09-47-43](https://user-images.githubusercontent.com/34654829/37635838-0b7101de-2c24-11e8-8c07-8853746252c8.png)

**Comment by gargshruti30** [comment]
@chutten Can I work on this issue?

**Comment by chutten** [comment]
Please do!

**Comment by gargshruti30** [comment]
@chutten okay I will do it.

**Comment by gargshruti30** [comment]
@chutten Is this okay ?
![screenshot from 2018-03-21 00-13-49](https://user-images.githubusercontent.com/34654829/37676014-c660ab70-2c9c-11e8-85c6-9bb216ad2d7d.png)

or should I move the report week button to the right corner like this ?
![screenshot from 2018-03-20 23-59-05](https://user-images.githubusercontent.com/34654829/37676059-e22753e0-2c9c-11e8-8258-6fdefb91d47c.png)

**Comment by chutten** [comment]
Most of the time I expect this dashboard to be loaded at 1024px wide or more, so whichever one looks nicest at that width. (I think aligning it to the right will look better)

**Comment by gargshruti30** [comment]
OK. I will make the required changes then.

**Comment by gargshruti30** [comment]
As suggested I have changed the position of report-week button to the right.
![screenshot from 2018-03-21 19-18-19](https://user-images.githubusercontent.com/34654829/37713356-ad55789a-2d3c-11e8-8ff7-afc35efe08c9.png)
I have made a PR.
@chutten Please review it.
