### ISSUE TITLE
X-axis values distort on changing screen size

### ISSUE THREAD

**Issue by gargshruti30** [mozilla/telemetry-dashboard#485]
In new-pipeline/dist.html, on decreasing the width of the screen the values on the x-axis of the graph shown, coincides with each other.

![screenshot from 2018-03-20 19-24-08-iloveimg-cropped](https://user-images.githubusercontent.com/34654829/37659078-fcef2522-2c74-11e8-99ba-dc32229f4812.png)

**Comment by chutten** [comment]
I wonder if this would be fixed if we used a newer version of metricsgraphics (our plotting library)... We could try it, if you feel up to it.

I recommend proceeding with caution, though. The last time we updated metricsgraphics there was a subtle bug in dates and times handling that we didn't catch for _months_. Any upgrade will require extensive testing.

**Comment by gargshruti30** [comment]
@chutten I would like to take it up as a point in my Outreachy application.

**Comment by chutten** [comment]
That's fair. Using up-to-date library versions and introducing tools and processes to keep them up-to-date long-term would be an excellent use of time during an outreachy term.
