### ISSUE TITLE
Rename "aurora" to  "dev edition" in dashboard-generator

### ISSUE THREAD

**Issue by Sylvia23** [mozilla/telemetry-dashboard#487]
https://telemetry.mozilla.org/dashboard-generator/

From #400 , I think the `Channel` name in the drop-down menu of `dashboard-generator` should be changed from "aurora" to "dev edition" as well.

@chutten, Should I take this up if it sounds right?

**Comment by chutten** [comment]
By all means, though mozilla/python_mozaggregator#69 may make it difficult to test, as it seems as though the aggregates service will be removing the aurora channel entirely.

**Comment by Sylvia23** [comment]
@chutten , Ohh I see, you mean it won't be functional while testing. But I can change the name from "aurora" to "dev edition" in the frontend. Did I got that right?

**Comment by chutten** [comment]
You can, but it might make more sense to just close this issue and work on something else. The "problem" of showing the word "aurora" -should- fix itself the next time the aggregator runs. (or, if the fix is service-level, it may have already fixed itself)

**Comment by Sylvia23** [comment]
@chutten , Yeah, got it. I will close it now.
