### ISSUE TITLE
The "permalink" button in probe-dictionary should be bold

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#505]
In the top menu bar, all other labels are bold. The "Get permalink" button should be bold too.

**Comment by Insiyaa** [comment]
I'd like to work on this!

**Comment by Sylvia23** [comment]
Hi there, You can see the code for `CSS` for `Get Permalink button` in `probe-dictionary` [here](https://github.com/mozilla/telemetry-dashboard/pull/450/files). It would be helpful to quickly solve the issue. Thanks!

**Comment by gargshruti30** [comment]
@georgf Can I work on this issue ?

**Comment by georgf** [comment]
Hi, i think Insiyaa was planning to work on this already.
