### ISSUE TITLE
Rename "Get Permalink" to "Get shortlink" in measurements dashboard

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#507]
In the [measurements dashboard](https://telemetry.mozilla.org/new-pipeline/dist.html), the "Get permalink" button actually get's you a "shortlink".
We should rename it to "Get shortlink" to avoid misunderstandings.

**Comment by Sylvia23** [comment]
@georgf , Sholud I give it a quick shot?

**Comment by ecomerford** [comment]
@georgf could I work on this? I could use an easy win while I'm trying to figure out #474

**Comment by ecomerford** [comment]
Wow @Sylvia23 that was weird! Haha I'll find something else to work on!

**Comment by Sylvia23** [comment]
Yeah ! Thanks @ecomerford !! Maybe because you wrote a little longer sentence @ecomerford . LOL !
