### ISSUE TITLE
Show only one TMO dashboard link in probe-dictionary

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#514]
Thanks to the tabbed interface from #409, we can now treat the TMO dashboard as one single dashboard.

That means that in detail views in probe-dictionary like [this one](https://telemetry.mozilla.org/probe-dictionary/?detailView=histogram%2FA11Y_CONSUMERS), we can just put one single link called "Measurements dashboard". This should link to the `dist.html` dashboard.

**Comment by Sylvia23** [comment]
You mean the Dashboard should be embedded in probe dictionary. Right?

**Comment by georgf** [comment]
I mean that we can just change the link. We currently have two links after "TMO dashboard" in the detail view, we can make it just one.

**Comment by Insiyaa** [comment]
Yes! Can I do this?

**Comment by Insiyaa** [comment]
This includes modification in getDatasetInfos function...

**Comment by georgf** [comment]
Sure!
