### ISSUE TITLE
Update TMO frontend to handle 405s from aggregator

### ISSUE THREAD

**Issue by robhudson** [mozilla/telemetry-dashboard#516]
In an upcoming aggregator deploy we've changed the API to return a 405 if we are passed filters that are not supported. The short list is:

    ALLOWED_DIMENSIONS = ('application', 'architecture', 'child', 'dates', 'label', 'metric', 'os', 'version')

If we receive a query string parameter, e.g. `?e10sEnabled=true` the API will return a 405 with the unsupported filter removed in the "Allow" header.

The front-end should probably or telemetry.js should probably bubble this up to the user.

**Comment by fbertsch** [comment]
https://github.com/mozilla/python_mozaggregator/pull/72

**Comment by Sylvia23** [comment]
Hi there, Can I give it a try. Is this issue somehow related to #411 #413 . Also, has there been a decision on what exactly is to be implemented for it? Any advice on where and how to get started with the implementation is also most welcome! Thanks!

**Comment by robhudson** [comment]
I would start in the file `v2/telemetry.js` and look for the `Telemetry.getJSON` calls. It could possibly be updated in `getJSON` itself to check for status code of 405 and catch the error there. Alternatively each callback passed to `getJSON` could handle it specifically.

This is related to #411 as it is the equivalent bug for the API. But it's also general in that now any unsupported query string will result in a 405 now, not just the `e10sEnabled` one.

**Comment by Sylvia23** [comment]
@robhudson @georgf  I had a doubt that `e10s` doesn't exsist in the entire dashboard frontend from #413  so how come can it appear in the `url`. So, what is point of talking of giving `error 405` on `?e10sEnabled=true`.  

Am I misunderstanding the issue? Please clarify. Thanks!

**Comment by robhudson** [comment]
It's not *just* `?e10sEnabled=true` but any filter in the URL that isn't supported on the API. So changing the front-end to understand 405 status codes from the API will help for now and in the future if there are any future changes.

Does that help?

**Comment by Sylvia23** [comment]
Thanks @robhudson !

How do you want the frontend to show the user about the `405 errors`?
Please tell @robhudson @georgf Thanks!

**Comment by Sylvia23** [comment]
@robhudson So what should I exactly implement for this issue? Only do `console.warn` for `405 errors`?
Please confirm. Thanks!

**Comment by robhudson** [comment]
Yes, I think what we decided what would be nice is when there is a 405 error, do the following:
* `console.warn` about the error
* redirect (or reissue) the request to what is in the "Allow" header, which will have the URL but without the bad query string.

**Comment by Sylvia23** [comment]
I am a little confused as to which `getJSON` call is handling passing filters, any guidance would be helpful.
I am guessing we should add a check for status 405 somewhere around [here](https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/v2/telemetry.js#L574) or maybe it can be handled [here](https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/v2/telemetry.js#L336). Please clarify on the correct `getJSON` call. 
Thanks!

**Comment by Sylvia23** [comment]
@robhudson @georgf @fbertsch I am unable to generate `405` responses even with manually adding parameters like `?e10sEnabled=true` to the aggregate query. I even rolled backed to commits before 7f0553dc2a5a2ee63b386cf1d82c35a32a0e0a6a and tested, still can't reproduce any 405 error. Can you verify this please?

**Comment by chutten** [comment]
@Sylvia23 The first getJSON call you linked (the one in `Telemetry.getFilterOptions`) won't need to be manipulated as channel and version are and always will be valid filters. You shouldn't expect a 405 there.

As for filters... according to [telemetry.js' docs](https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/v2/doc.md) filters are passed to the `getEvolution` call, which is implemented [over here](https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/v2/telemetry.js#L506). 

You may be unable to generate 405 responses because the change isn't yet on the production aggregates.tmo server. I think it's on the staging server, whose address I don't have at the moment. @robhudson or @fbertsch will have that hostname handy.

**Comment by Sylvia23** [comment]
Thanks for the information @chutten . From the `getEvolution` function I understand that `populateEntriesMap` is being called which is doing the `getJSON` call, so I believe the check for 405 should go into [this call](https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/v2/telemetry.js#L478). Is that right? @chutten

**Comment by fbertsch** [comment]
@Sylvia23 @chutten is correct, we haven't pushed this change to production because the client isn't ready yet. 

Sylvia, you can access the staging service where the changes are available at `https://mozaggregator.stage.mozaws.net`

**Comment by robhudson** [comment]
Here's an example URL that will 405 against stage:
`/aggregates_by/build_id/channels/nightly/?metric=GC_MS&version=59&application=Firefox&os=Windows_NT&architecture=x86-64&dates=20180101&foo=bar`

If you view that in the network panel and inspect the headers you'll see an "Allow" header with the `'&foo=bar'` removed resulting in a URL that should return a 200.

I don't know the Javascript well enough to point you to where that kind of URL would be generated and where to handle the error code. I would look to @chutten for that.

**Comment by chutten** [comment]
The filter string for the URL is only generated here: https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/v2/telemetry.js#L518

Trying the request again with a new URL will require some extra work, but since we can trust the server to hand us the proper url this time, we can probably just pass it into another `getJSON` call using the existing callback et voila.

**Comment by Sylvia23** [comment]
Yes @chutten that is the correct place of the URL generation. I have made a PR #535 making changes to handle the 405 errors.
However I am having trouble accessing the correct URL in the Allow header as I have commented in the PR. Could please check on that? Thanks!
