### ISSUE TITLE
Probe name goes beyond the page

### ISSUE THREAD

**Issue by Insiyaa** [mozilla/telemetry-dashboard#518]
When the probe name is too long, it goes beyond the page like [this](https://telemetry.mozilla.org/probe-dictionary/?detailView=histogram%2FCACHE_SERVICE_LOCK_WAIT_MAINTHREAD_NSCACHEENTRYDESCRIPTOR_GETCLIENTID). It should be displayed in the page limit...

**Comment by Insiyaa** [comment]
Maybe something like this? 
![screenshot-2018-3-30 firefox probe dictionary - find probes](https://user-images.githubusercontent.com/29259374/38136238-cf4353a0-343a-11e8-832f-e550ca8fac03.png)
But here the position of 'x' doesn't feel right?

**Comment by georgf** [comment]
That's a good point, thanks for bringing that up.
Did you want to work on this @Insiyaa ?

The proposal looks good, although yes, the 'x' could be on top?

**Comment by Insiyaa** [comment]
Yes I'll work on this!
