### ISSUE TITLE
The description text and detail link should have a smaller (normal) font size in Measurement Dashboard

### ISSUE THREAD

**Issue by Sylvia23** [mozilla/telemetry-dashboard#521]
#406 #501 For a better user experience, the description text and detail link should have a smaller (normal) font size in Measurement Dashboard.

**Comment by georgf** [comment]
Thanks for opening this!
Are you interested to work on this @Sylvia23?

**Comment by Sylvia23** [comment]
Yes! I will start working on it now and report back in a while. Thanks!

**Comment by georgf** [comment]
Ok, cheers.
