### ISSUE TITLE
Probe dictionary stats should only count "release" probes for release channel

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#526]
In the stats view, we currently count all the probes for the release channel.
We don't record all of them there, so we should show only count the "release" probes.

Compare e.g. [the count here](https://telemetry.mozilla.org/probe-dictionary/?optout=true&channel=release&version=59) (55) with [the count here](https://telemetry.mozilla.org/probe-dictionary/?optout=true&channel=release&version=59&view=stats-view) (>1.8k for version 59).

**Comment by Insiyaa** [comment]
Can you please explain a bit more?

**Comment by Sylvia23** [comment]
@Insiyaa  According to my understanding, the issue says that when the `view` is set to `stats`, the `Count of recorded probes` displays as `1.8k probes` for `version 59` while the actual count is `550` for `version 59` as shown in the screen-shot attached below. Please have a look. 
Hence, there is some `bug` which counts for all values even when the `channel` is set to `release` and gives a high value ie `1.8k`.
So, we should make them equal and show the actual count ie `550` in the histogram ie `stats view` as well.
Does that help?
![imageedit_2_8936431124](https://user-images.githubusercontent.com/23060217/38490883-f11838cc-3c07-11e8-8062-fab02a7eecba.png) ![imageedit_3_7244767032](https://user-images.githubusercontent.com/23060217/38490885-f147608e-3c07-11e8-9bf7-d388ad9a7d7d.png)

@georgf Did I get that right? Please clarify.
Thanks!

**Comment by Insiyaa** [comment]
@Sylvia23 Thanks:)! I'll try to look into this!

**Comment by Sylvia23** [comment]
Cool. Cheers !

**Comment by Insiyaa** [comment]
Is something like this expected? @georgf 
![moz0](https://user-images.githubusercontent.com/29259374/38631170-a56f0f74-3dd6-11e8-9e33-5b29ea1dfb2b.png)

**Comment by georgf** [comment]
Yes, this is exactly what i would expect!
It would be nice to change the style (only show blue bars for this case), but that is just a cosmetic issue :)

**Comment by Insiyaa** [comment]
Yes will do that! And what is to be done with the legend? Is it to be removed?

**Comment by georgf** [comment]
We could leave it, but only show "optout". Does that sound good?

**Comment by Insiyaa** [comment]
Yea okay!
