### ISSUE TITLE
Add a bug icon to the "report a bug" link on the landing page

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#533]
This would make it easier to recognize the link.
We can use the font-awesome bug icon for that.

**Comment by Sylvia23** [comment]
I would like to give it a quick shot meanwhile solving #516 Thanks!

**Comment by Sylvia23** [comment]
@georgf It should be closed from #534 Thanks!

**Comment by georgf** [comment]
Cheers!
