### ISSUE TITLE
Use standard naming pattern in probe-dictionary code

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#539]
In `probe-dictionary/explore.js`, we mix two different [naming conventions](https://en.wikipedia.org/wiki/Naming_convention_(programming)), `camelCase` (e.g. `version_constraint`) and underscore-separated words (e.g. `channelInfo`).

We should standardize on camel-case where possible.

**Comment by georgf** [comment]
Before merging this change in, we probably want to let #532 merge first.

**Comment by Insiyaa** [comment]
I'd like to do this as well...

**Comment by georgf** [comment]
Fixed by #545.
