### ISSUE TITLE
Improve probe-dictionary code encapsulation

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#547]
Currently the JS code in `probe-dictionary/` is not structured very well.
Especially the logic around using `gProbeData` is spread around the whole `explore.js` file, making it hard to understand what exactly is going on.

We should improve this, starting with `gProbeData`. This would mean:
- Introducing a new class to encapsulate an individual probes info, e.g. `class Probe`.
- Looking through the current code what we use from `gProbeData`.
- For each use-case identified, add properties or methods to the `Probe` class or extend existing ones.
- Make the code only access probe logic through the `Probe` class, removing any direct access to `gProbeData`.

**Comment by georgf** [comment]
@Insiyaa Would this issue be interesting for you?

**Comment by Insiyaa** [comment]
Yes. I'd like to work on this. Thanks!

**Comment by georgf** [comment]
Great, ok!
One tip on this issue:

Proposing a design first (class methods and what they are used for) probably will save us some review time later.

**Comment by Insiyaa** [comment]
Okay👍

**Comment by Insiyaa** [comment]
After going through the code I understand that the `class Probe` will have a method which will return data at a particular index provided as an argument and would return the complete `gProbeData` when no arguments given. Is this appropriate?

**Comment by georgf** [comment]
Sorry for the late response, i was busy with a training.

I think the `class Probe` should encapsulate the `gProbeData` contents.
We could e.g. have a function `getProbe(id)`, that returns `new Probe(gProbeData[id])`.

`class Probe` would have some methods and properties, that hide the logic using `gProbeData` we currently have in other places.
So, for example. Let's say we get this as `var probe = getProbe(id)`, then:
- [the logic here](https://github.com/mozilla/telemetry-dashboard/blob/ab40fa52500ce3e0b11cc36e69ede8f55358b26a/probe-dictionary/explore.js#L700-L705) could be hidden in a method and this code just says `var link = probe.getTmoDashboardLink(); if (link) ...`
- [`friendlyRecordingRangeHistory()`](https://github.com/mozilla/telemetry-dashboard/blob/ab40fa52500ce3e0b11cc36e69ede8f55358b26a/probe-dictionary/explore.js#L442) could be a method and be used [here](https://github.com/mozilla/telemetry-dashboard/blob/ab40fa52500ce3e0b11cc36e69ede8f55358b26a/probe-dictionary/explore.js#L868) as `probe.friendlyRecordingRangeForChannel()`

Does that make sense?

And as a resource: [Background on JavaScript classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#9)

**Comment by chutten** [comment]
@Insiyaa Are you still working on this? Is there anything we can help with?

**Comment by Insiyaa** [comment]
I didn't get the chance to work on this as I was busy with some courses. I'll try to work for this-this week. Sorry for the delay.

**Comment by chutten** [comment]
Deprioritizing and unassigning due to inactivity. @Insiyaa if you find the time later on, just let us know and I'll reassign this to you.

**Comment by ab0092** [comment]
@chutten , @georgf  i have made an initial design of the **Probe** Class and it should look something like this 

`class Probe 
{
 // This property will consist of the Total Probe Data that is being Populated during Page initialisation
  ProbeData;

// This method will set Value to the ProbeData Property **(new mthod to be added)**
setProbeData(probeData);

// This method will be used to set value to the ProbeData Property by a specific ProbeId **(new mthod to be added)**
setProbeDataById(probeid);

// This method will be used to get value to the ProbeData Property by its ProbeId **(new mthod to be added)**
getProbeDataById(probeid);

// This method will be used to return the Probe data in a sorted format of its keys **(use case : line 536 in explore.js)** **(new mthod to be added)**
sortProbeDataByKeys();

// This method is currently being used to get probeid **(existing method)**
findProbeIdFromCaseInsensitive(probeid);

}`

Apart from these methods there are some other methods  **renderProbeStats, friendlyRecordingRangeForHistory** but i am not sure if these methods should also be encapsulated, so i would require some help regarding this. 

Please let me know if i missed out anything here. Thanks

**Comment by wlach** [comment]
Closing this issue, probe-dictionary is now maintained in https://github.com/mozilla/probe-dictionary/ and I believe this is no longer relevant.

Thanks for everyone's work on this!
