### ISSUE TITLE
Add experimenter to Telemetry portal

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#548]
Experimenter is live now from what i understand, so we should link it from our [portal page](https://telemetry.mozilla.org/).

@rafrombrc, does that sound right?
Can you give the correct link and a short description?

**Comment by jaredlockhart** [comment]
Yes we should!  The link is here:

https://experimenter.services.mozilla.com/

Description:

Experimenter is a platform for creating, monitoring, and reviewing Shield studies that target Firefox desktop users.
