### ISSUE TITLE
Fix link to gfx telemetry dashboard

### ISSUE THREAD

**Issue by georgf** [mozilla/telemetry-dashboard#556]
The link to the gfx telemetry dashboard on the portal page is dead (dvander left us).

Following the repo link [here](https://wiki.mozilla.org/Platform/GFX/Telemetry#moz-gfx-telemetry), it looks like [jrmuizel now owns it](https://github.com/jrmuizel/moz-gfx-telemetry).
We should check with him where it is published and change the link accordingly.

**Comment by chutten** [comment]
@jrmuizel do you have a canonical link for this dashboard? What's its future?

**Comment by shiri1248** [comment]
I would like to work on this issue. Can anyone guide me please

**Comment by chutten** [comment]
Hi! 

The "Graphics Telemetry" dashboard linked to in the index can't be found at the provided link any more. Instead it can be found here: https://firefoxgraphics.github.io/telemetry/

This Issue is about changing the link to point to the new address. Please let me know if you have any questions.

**Comment by shiri1248** [comment]
Thanks @chutten  for your information. Is this issue belongs to same repo or any other? Please clarify my doubt .

**Comment by chutten** [comment]
This issue is in this repo. The broken link we want fixed is this one.... wait a minute.

It appears as though this was fixed recently. Looks like it was handled by #569, but this issue wasn't closed. We can close this now.

Would you like to work on #575 instead? I see you commented there as well.

**Comment by shiri1248** [comment]
yes @chutten  I will work on #575.
