### ISSUE TITLE
USER_CHROME_CSS_LOADED appears for Nightly 60-63 and Beta 59-61 but not for any Developer Edition builds on the Evolution Dashboard

### ISSUE THREAD

**Issue by msujaws** [mozilla/telemetry-dashboard#565]
I am able to select USER_CHROME_CSS_LOADED and then select Nightly 60-63 or beta 59-61, but when I switch the builds to Developer Edition then the histogram ID gets reset.

This histogram was introduced in Nightly 59 by https://bugzilla.mozilla.org/show_bug.cgi?id=1416044

**Comment by msujaws** [comment]
This histogram ID also doesn't appear on the Measurement Dashboard for Developer Edition builds.

**Comment by msujaws** [comment]
@nt1m pointed out to me that this histogram was uplifted to Firefox 58 during the 58 beta cycle.

**Comment by fbertsch** [comment]
@msujaws Thanks for reporting! We found that Dev Edition data isn't up-to-date, see bug 1476323 for details. In the meantime, will the beta data suffice for your use case?

**Comment by fbertsch** [comment]
@msujaws this has been fixed, we're now aggregating dev edition data again. Please take a look at your charts, there should be data from the last few days. If everything looks to be in order, feel free to close this issue!

**Comment by msujaws** [comment]
Thank you, I can confirm that this is now fixed.
