### ISSUE TITLE
Add UI to Dashboard Generator to select Evolution Bucket Index

### ISSUE THREAD

**Issue by chutten** [mozilla/telemetry-dashboard#572]
With #571 we now have in dashgen and wrapper a facility for configuring the bucket index we want an evolution to display. However, we do not have a way in the dashgen UI to select one.

This bug is to add an input field, probably of type="number", to the evolution tab of Dashboard Generator which defaults to 0 and which plumbs into the `evoBucketIndex` param in wrapper as implemented in #571 .

**Comment by chutten** [comment]
@ab0092 has expressed an interest in working on this.

**Comment by ab0092** [comment]
@chutten i have added the UI for the bucketindex. Changes are available here **https://ab0092.github.io/telemetry-dashboard/dashboard-generator/index.html** please have a look and let me know if anything more is to be added.

**Comment by chutten** [comment]
Seems to work and have no bad interactions with the other parameters. Looks good from the outside.

**Comment by ab0092** [comment]
Should i make the PR for you to merge it??

**Comment by chutten** [comment]
Yes please. 

In fact, if you'd like to save a step in future, you can submit the PR directly when you think you have it ready. I can evaluate the live demo and the code at the same time that way and save you from having to wait for me to get back to you : )

**Comment by ab0092** [comment]
Ok i will certainly do that. Thanks. :-)
