### ISSUE TITLE
Dev edition charts show up as "aurora" in chart labels

### ISSUE THREAD

**Issue by robhudson** [mozilla/telemetry-dashboard#575]
Visit https://mzl.la/2BaArYT and hover the chart lines and look at the labels. Since the front-end is already changing "Aurora" to "Dev Edition" elsewhere I propose the front-end does the string swap here as well.

**Comment by shiri1248** [comment]
I would like to work on this.

**Comment by shiri1248** [comment]
can anyone  guide me on this issue please

**Comment by chutten** [comment]
Yes. The code controlling what plots look like can be found in `new-pipeline/src/dist.js` and `new-pipeline/src/evo.js`. Any time it uses the word "aurora" in a place where it might be shown to a user it should instead read "dev edition"

**Comment by shiri1248** [comment]
Thanks @chutten , so I should replace the  word  "aurora" to  "dev edition" am I right?

**Comment by chutten** [comment]
Correct.

**Comment by shiri1248** [comment]
@chutten  submitted a PR #576  please review and  if you find any conflicts please let me  know

**Comment by hardik25** [comment]
@chutten 

How to reproduce this issue?

**Comment by hardik25** [comment]
Hi @chutten 

I have created a pull request with fix to this issue. Please review.

**Comment by driver-by** [comment]
Hi guys,
I've  submitted a PR #629 to fix the issue. Waiting for review.
Thanks!
