### ISSUE TITLE
support ClientID

### ISSUE THREAD

**Issue by monicachew** [mozilla/telemetry-dashboard#61]
Now that telemetry includes ClientID, it should be supported in telemetry.js

http://robertovitillo.com/2014/12/19/clientid-in-telemetry-submissions/

**Comment by jonasfj** [comment]
We can't expose this before it's computed in the telemetry analysis jobs. As roberto says, this is next get stuff.

I'm not longer working actively on telemetry; but this will require some re-architecting of the current analysis framework. So it probably won't happen anytime soon.

**Comment by fbertsch** [comment]
We won't be including clientId in TMO.
