### ISSUE TITLE
evolution graph shows weird line

### ISSUE THREAD

**Issue by staktrace** [mozilla/telemetry-dashboard#621]
Go to https://mzl.la/2UgDjaU

Observe how the line from Nightly 65 takes a nosedive into Nightly 67 (see attached screenshot). What's with that?

<img width="1158" alt="nosedive" src="https://user-images.githubusercontent.com/485789/56086828-ca78d800-5e2c-11e9-9ede-e4a6f1b40d19.png">

**Comment by chutten** [comment]
According to the aggregates dataset we received 31M samples from 8.9k pings from a build identifying itself as Nightly 65 with buildid that started with 20190211. 

As to the reasonable follow-up question "What?" I have no answer. I'm willing to bet if we look closely into the pings submitted by these clients we'll be left with only more questions. For instance, if we look at only Mac and Linux data, there's none from that build. They're all Windows users, predominantly (but not completely) from Windows 8.1. Maybe it's [That Aurora 51 Client](https://chuttenblog.wordpress.com/2017/02/23/data-science-is-hard-anomalies-and-what-to-do-about-them/) all over again where there's one client (possibly multiple machines with cloned profiles) identifying as a weird build only on certain outdated versions of Windows.

It is safe to ignore.
