### ISSUE TITLE
Probes that are desktop-only don't provide useful error for mobile on telemetry.m.o

### ISSUE THREAD

**Issue by staktrace** [mozilla/telemetry-dashboard#623]
Go to e.g. https://mzl.la/2ZqFJHV and then in the selector sentence at the top, try changing "Firefox Desktop" to "Firefox Mobile".

Expected: the histogram goes away, or gives you some indication that this probe is not recorded on mobile.

Actual: histogram remains pretty much where it is, showing the desktop numbers.

The problem is more obvious if you go to the mobile stats for a different probe, e.g. https://mzl.la/2ZotGL6 and then switch the probe name to FX_TAB_SWITCH_COMPOSITE_E10S_MS - it will keep showing the old probe data.

**Comment by chutten** [comment]
Might be another aspect of the same underlying problem as #606. We should retest after it is addressed.
