### ISSUE TITLE
Index should document how to edit the index

### ISSUE THREAD

**Issue by tdsmith** [mozilla/telemetry-dashboard#650]
I didn't realize this repo and the t.m.o front page were connected. It'd be great to have a "edit me!" link on the t.m.o home page.

**Comment by chutten** [comment]
Sure. https://github.com/mozilla/telemetry-dashboard/commit/7ae4da668d360b591bc65c301c4981d105c0b4b8 ought to take care of it. Check back in 15min or so when the caches flush and we should be up and running.
