### ISSUE TITLE
Dashboard links should point to an HTML file

### ISSUE THREAD

**Issue by mikaeld** [mozilla/telemetry-dashboard#667]
## Description
The Data SRE team recently [migrated this project's infrastructure from AWS to GCP](https://github.com/mozilla-it/webservices-infra/pull/109). While assessing our migration, we've noticed some links pointing to a directory rather than an HTML file (_see examples below_). 

~I can't recall if the links were working before the migration. It is possible that AWS CloudFront automatically rewrote URLs to `index.html` and that the GCP equivalent does not.~ _Edit_: The previous setup was relying on an AWS feature called [S3 website endpoint](https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteEndpoints.html). Using that endpoint URL returns the default index document that you configure for the website. However Amazon S3 website endpoints do not support HTTPS or access points, which is why we can't use it with this GCP migration.

We could handle this by manually specifying path matching rules to enforce url rewrites, however this would mean an infrastructure re-deployment every time a new link is added. This is not an ideal fix for the issue

It would be preferable to simply change the links in this project. Links like _Measurement Dashboard_ and _Dashboard Generator_ already point to their HTML files.

## Examples 
- **Histogram Simulator** 
  - points to https://telemetry.mozilla.org/histogram-simulator/
  - should be https://telemetry.mozilla.org/histogram-simulator/index.html
- **Update Orphaning** 
  - points to https://telemetry.mozilla.org/update-orphaning/
  - should be https://telemetry.mozilla.org/update-orphaning/index.html

Thanks!

**Comment by chutten** [comment]
Fixed by #668
